-- Complete admin-configurable public event experience. Existing RSVP and slot rows are untouched.
ALTER TABLE `events` ADD COLUMN `custom_label` text NOT NULL DEFAULT '';
ALTER TABLE `events` ADD COLUMN `short_description` text NOT NULL DEFAULT '';
ALTER TABLE `events` ADD COLUMN `offer` text NOT NULL DEFAULT '';
ALTER TABLE `events` ADD COLUMN `offer_details` text NOT NULL DEFAULT '';
ALTER TABLE `events` ADD COLUMN `offer_terms` text NOT NULL DEFAULT '';
ALTER TABLE `events` ADD COLUMN `event_date` text NOT NULL DEFAULT '';
ALTER TABLE `events` ADD COLUMN `start_time` text NOT NULL DEFAULT '';
ALTER TABLE `events` ADD COLUMN `end_time` text NOT NULL DEFAULT '';
ALTER TABLE `events` ADD COLUMN `all_day` integer NOT NULL DEFAULT 0;
ALTER TABLE `events` ADD COLUMN `location_details` text NOT NULL DEFAULT '';
ALTER TABLE `events` ADD COLUMN `directions_url` text NOT NULL DEFAULT '';
ALTER TABLE `events` ADD COLUMN `unlimited_capacity` integer NOT NULL DEFAULT 0;
ALTER TABLE `events` ADD COLUMN `allow_guest_names` integer NOT NULL DEFAULT 0;
ALTER TABLE `events` ADD COLUMN `registration_opens_date` text NOT NULL DEFAULT '';
ALTER TABLE `events` ADD COLUMN `registration_opens_time` text NOT NULL DEFAULT '';
ALTER TABLE `events` ADD COLUMN `registration_closes_date` text NOT NULL DEFAULT '';
ALTER TABLE `events` ADD COLUMN `registration_closes_time` text NOT NULL DEFAULT '';
ALTER TABLE `events` ADD COLUMN `appointment_recommended` integer NOT NULL DEFAULT 0;
ALTER TABLE `events` ADD COLUMN `cost_type` text NOT NULL DEFAULT '';
ALTER TABLE `events` ADD COLUMN `cta_label` text NOT NULL DEFAULT '';
ALTER TABLE `events` ADD COLUMN `cta_action` text NOT NULL DEFAULT '';
ALTER TABLE `events` ADD COLUMN `cta_url` text NOT NULL DEFAULT '';
ALTER TABLE `events` ADD COLUMN `cta_email` text NOT NULL DEFAULT '';
ALTER TABLE `events` ADD COLUMN `cta_phone` text NOT NULL DEFAULT '';
ALTER TABLE `events` ADD COLUMN `sharing_enabled` integer NOT NULL DEFAULT 1;
ALTER TABLE `events` ADD COLUMN `share_message` text NOT NULL DEFAULT '';
UPDATE `events` SET `category`='' WHERE `category`='Store Event';
UPDATE `events` SET `attendance_type`='' WHERE `attendance_type`='In person';
