"use client";
import { useCallback, useEffect, useState } from "react";

type Status = "pending" | "change_proposed" | "confirmed" | "declined";
type Booking = { id:string; publicReference:string; status:string; pendingSince:string; requestedStartAt:string; proposedStartAt:string|null; clientName:string; clientEmail:string; serviceName:string; holdActive:boolean; overdue:boolean };
type Detail = Booking & { clientPhone:string; returningClient:boolean; howHeard:string|null; ageRange:string|null; profileType:string|null; eventType:string|null; eventDate:string|null; bookingNotes:string|null; activeHoldStartsAt:string|null };
type History = { id:string; fromStatus:string|null; toStatus:string; actorType:string; reason:string|null; createdAt:string };
const tabs: Array<{value:Status;label:string}> = [{value:"pending",label:"Pending"},{value:"change_proposed",label:"Time proposed"},{value:"confirmed",label:"Confirmed"},{value:"declined",label:"Declined"}];
const fmt=(value:string|null)=>value?new Intl.DateTimeFormat("en-US",{timeZone:"America/Boise",dateStyle:"medium",timeStyle:"short"}).format(new Date(value)):"—";
function boiseLocalToIso(value:string){const [date,time]=value.split("T"),[year,month,day]=date.split("-").map(Number),[hour,minute]=time.split(":").map(Number),target=Date.UTC(year,month-1,day,hour,minute);let epoch=target;for(let i=0;i<4;i++){const parts=new Intl.DateTimeFormat("en-US",{timeZone:"America/Boise",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hourCycle:"h23"}).formatToParts(epoch),part=(type:string)=>Number(parts.find(item=>item.type===type)?.value),represented=Date.UTC(part("year"),part("month")-1,part("day"),part("hour"),part("minute")),correction=target-represented;epoch+=correction;if(!correction)break;}return new Date(epoch).toISOString();}

export default function AdminDashboard({userName,signOutPath}:{userName:string;signOutPath:string}) {
  const [status,setStatus]=useState<Status>("pending"),[bookings,setBookings]=useState<Booking[]>([]),[selected,setSelected]=useState<string>(""),[detail,setDetail]=useState<Detail|null>(null),[history,setHistory]=useState<History[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[action,setAction]=useState<"decline"|"propose-time"|null>(null),[reason,setReason]=useState(""),[proposed,setProposed]=useState("");
  const loadList=useCallback(async()=>{setLoading(true);setError("");try{const r=await fetch(`/api/admin/bookings?status=${status}`,{cache:"no-store"}),p=await r.json() as {data:{bookings:Booking[]};error?:{message?:string}};if(!r.ok)throw new Error(p.error?.message);setBookings(p.data.bookings);setSelected(current=>p.data.bookings.some((b:Booking)=>b.id===current)?current:(p.data.bookings[0]?.id||""));}catch(e){setError(e instanceof Error?e.message:"Requests could not be loaded.");}finally{setLoading(false);}},[status]);
  const loadDetail=useCallback(async()=>{if(!selected){setDetail(null);setHistory([]);return;}try{const r=await fetch(`/api/admin/bookings/${selected}`,{cache:"no-store"}),p=await r.json() as {data:{booking:Detail;history:History[]};error?:{message?:string}};if(!r.ok)throw new Error(p.error?.message);setDetail(p.data.booking);setHistory(p.data.history);}catch(e){setError(e instanceof Error?e.message:"Request details could not be loaded.");}},[selected]);
  useEffect(()=>{void Promise.resolve().then(loadList);},[loadList]); useEffect(()=>{void Promise.resolve().then(loadDetail);},[loadDetail]);
  async function mutate(name:"confirm"|"decline"|"release-hold"|"propose-time") { if(!detail)return;setError("");try{const body:Record<string,unknown>={expectedStatus:detail.status,reason:reason||null};if(name==="propose-time")body.requestedStartAt=boiseLocalToIso(proposed);const r=await fetch(`/api/admin/bookings/${detail.id}/${name}`,{method:"POST",headers:{"content-type":"application/json","idempotency-key":crypto.randomUUID()},body:JSON.stringify(body)}),p=await r.json() as {error?:{message?:string}};if(!r.ok)throw new Error(p.error?.message);setAction(null);setReason("");setProposed("");await loadList();}catch(e){setError(e instanceof Error?e.message:"The request could not be updated.");}}
  return <main className="admin-shell">
    <header className="admin-header"><div><p className="eyebrow">STYLE WITH KAYLA</p><h1>Appointment requests</h1><p>Signed in as {userName}</p></div><a href={signOutPath}>Sign out</a></header>
    <nav className="admin-tabs">{tabs.map(tab=><button key={tab.value} className={status===tab.value?"active":""} onClick={()=>{setStatus(tab.value);setSelected("");}}>{tab.label}</button>)}</nav>
    {error&&<p className="booking-error" role="alert">{error}</p>}
    <div className="admin-layout"><section className="request-list" aria-label="Appointment requests">{loading?<p>Loading requests…</p>:bookings.length?bookings.map(b=><button key={b.id} className={selected===b.id?"selected":""} onClick={()=>setSelected(b.id)}><span><strong>{b.clientName}</strong>{b.overdue&&<i>Overdue</i>}</span><span>{b.serviceName}</span><span>{fmt(b.proposedStartAt||b.requestedStartAt)}</span><small>{b.publicReference} · {b.holdActive?"Time held":"No active hold"}</small></button>):<p>No {status.replace("_"," ")} requests.</p>}</section>
      <section className="request-detail">{detail?<><div className="detail-heading"><div><p className="small-label">{detail.publicReference}</p><h2>{detail.clientName}</h2><p>{detail.serviceName}</p></div><span className={`status-pill ${detail.status}`}>{detail.status.replace("_"," ")}</span></div>
        <dl><div><dt>Requested time</dt><dd>{fmt(detail.requestedStartAt)}</dd></div><div><dt>Active hold</dt><dd>{fmt(detail.activeHoldStartsAt)}</dd></div><div><dt>Contact</dt><dd><a href={`mailto:${detail.clientEmail}`}>{detail.clientEmail}</a><br/>{detail.clientPhone}</dd></div><div><dt>Client</dt><dd>{detail.returningClient?"Returning client":`New client · ${detail.howHeard||"source not provided"}`}</dd></div>{detail.profileType&&<div><dt>Profile route</dt><dd>{detail.profileType.replace("_"," ")}</dd></div>}{detail.eventType&&<div><dt>Event</dt><dd>{detail.eventType} · {detail.eventDate}</dd></div>}{detail.bookingNotes&&<div className="wide"><dt>Notes</dt><dd>{detail.bookingNotes}</dd></div>}</dl>
        {(detail.status==="pending"||detail.status==="change_proposed")&&<div className="admin-actions"><button className="primary-button" disabled={!detail.activeHoldStartsAt||!detail.profileType} onClick={()=>void mutate("confirm")}>Confirm appointment</button><button onClick={()=>setAction("propose-time")}>Propose another time</button>{detail.activeHoldStartsAt&&<button onClick={()=>void mutate("release-hold")}>Release hold</button>}<button className="danger" onClick={()=>setAction("decline")}>Decline</button></div>}
        {action&&<div className="action-panel"><h3>{action==="decline"?"Decline request":"Propose another time"}</h3>{action==="propose-time"&&<label>Boise date and time<input type="datetime-local" value={proposed} onChange={e=>setProposed(e.target.value)}/></label>}<label>Reason {action==="decline"&&"*"}<textarea value={reason} onChange={e=>setReason(e.target.value)}/></label><div><button onClick={()=>setAction(null)}>Cancel</button><button className="primary-button" disabled={(action==="decline"&&!reason)||(action==="propose-time"&&!proposed)} onClick={()=>void mutate(action)}>Save</button></div></div>}
        <div className="history"><h3>Request history</h3>{history.map(item=><p key={item.id}><strong>{item.toStatus.replace("_"," ")}</strong> · {fmt(item.createdAt)}{item.reason&&<><br/>{item.reason}</>}</p>)}</div></>:<p>Select a request to review it.</p>}</section></div>
  </main>;
}
