"use client";
import { useState } from "react";

type Insight={id?:string;polarity:"worked"|"didnt_work";category:string;insightText:string;clientFacing:boolean;importance:string|null;savedToClientNotes?:boolean;clientStyleNoteId?:string|null};
type Item={id?:string;itemName:string;brand:string|null;size:string|null;color:string|null;category:string|null;note:string|null;disposition:"purchased"|"considered";clientFacing:boolean};
type Formula={id?:string;formulaText:string;explanation:string|null};
type Priority={id?:string;category:string|null;priorityText:string;status:string;clientFacing:boolean};
export type RecapDocument={recap:{status:string;outcome:string|null;whatWeSolved:string|null;kaylaNote:string|null;nextMomentServiceType:string|null;nextMomentTiming:string|null;nextMomentReason:string|null;nextMomentBookingCtaEnabled:boolean;privateFollowUpNote:string|null};insights:Insight[];items:Item[];formulas:Formula[];priorities:Priority[]};
const categories=["fit","silhouette","color","fabric","comfort","brand","size","styling","lifestyle","preference","other"];
const blankInsight=(polarity:Insight["polarity"]):Insight=>({polarity,category:"other",insightText:"",clientFacing:true,importance:null});
const patch=<T,>(rows:T[],index:number,value:Partial<T>)=>rows.map((row,i)=>i===index?{...row,...value}:row);
export default function RecapWrapUp({bookingId,initial,onError}:{bookingId:string;initial:RecapDocument;onError:(message:string)=>void}){
 const [doc,setDoc]=useState(initial),[saving,setSaving]=useState(false),[message,setMessage]=useState("");
 const scalar=(value:Partial<RecapDocument["recap"]>)=>setDoc(current=>({...current,recap:{...current.recap,...value}}));
 async function save(status:string){setSaving(true);setMessage("");onError("");try{const response=await fetch(`/api/admin/bookings/${bookingId}/recap`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({...doc.recap,status,insights:doc.insights.map(row=>({id:row.id,polarity:row.polarity,category:row.category,insightText:row.insightText,clientFacing:row.clientFacing,importance:row.importance})),items:doc.items,formulas:doc.formulas,priorities:doc.priorities})});const payload=await response.json() as {data?:RecapDocument;error?:{message?:string;fieldErrors?:Record<string,string>}};if(!response.ok)throw new Error(Object.values(payload.error?.fieldErrors??{})[0]||payload.error?.message);setDoc(payload.data!);setMessage(status==="ready_for_review"?"Ready for review.":"Draft saved.");}catch(error){onError(error instanceof Error?error.message:"The recap could not be saved.");}finally{setSaving(false);}}
 async function promote(index:number){const insight=doc.insights[index];if(!insight.id)return;try{const response=await fetch(`/api/admin/bookings/${bookingId}/recap/promote-insight`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({insightId:insight.id})});const payload=await response.json() as {data?:{clientStyleNoteId:string};error?:{message?:string}};if(!response.ok)throw new Error(payload.error?.message);setDoc(current=>({...current,insights:patch(current.insights,index,{savedToClientNotes:true,clientStyleNoteId:payload.data!.clientStyleNoteId})}));}catch(error){onError(error instanceof Error?error.message:"The insight could not be saved to the client profile.");}}
 const insightSection=(polarity:Insight["polarity"],title:string)=>{const indexed=doc.insights.map((row,index)=>({row,index})).filter(({row})=>row.polarity===polarity);return <fieldset><legend>{title}</legend>{indexed.map(({row,index})=><div className="recap-repeat-row" key={row.id??index}><select aria-label={`${title} category`} value={row.category} onChange={e=>setDoc(c=>({...c,insights:patch(c.insights,index,{category:e.target.value})}))}>{categories.map(value=><option key={value} value={value}>{value.replace("_"," ")}</option>)}</select><textarea aria-label={`${title} insight`} maxLength={500} value={row.insightText} onChange={e=>setDoc(c=>({...c,insights:patch(c.insights,index,{insightText:e.target.value})}))}/><label><input type="checkbox" checked={row.clientFacing} onChange={e=>setDoc(c=>({...c,insights:patch(c.insights,index,{clientFacing:e.target.checked})}))}/> Client-facing</label>{row.id&&(row.savedToClientNotes?<span>Saved to profile</span>:<button type="button" onClick={()=>void promote(index)}>Save to Client Style Profile</button>)}<button type="button" onClick={()=>setDoc(c=>({...c,insights:c.insights.filter((_,i)=>i!==index)}))}>Remove</button></div>)}<button type="button" onClick={()=>setDoc(c=>({...c,insights:[...c.insights,blankInsight(polarity)]}))}>Add {title.toLowerCase()} insight</button></fieldset>};
 return <div className="action-panel recap-wrap-up"><h3>Complete Appointment Wrap-Up</h3>
  <label>Outcome<select value={doc.recap.outcome??""} onChange={e=>scalar({outcome:e.target.value||null})}><option value="">Choose…</option><option value="great_success">Great success</option><option value="good_progress">Good progress</option><option value="partial_success">Partial success</option><option value="research_needed">Research needed</option><option value="no_purchase_useful_discovery">No purchase, useful discovery</option></select></label>
  <label>What did we solve today?<textarea maxLength={2000} value={doc.recap.whatWeSolved??""} onChange={e=>scalar({whatWeSolved:e.target.value})}/></label>
  {insightSection("worked","What Worked")}{insightSection("didnt_work","What Didn't Work")}
  <fieldset><legend>Items Added</legend>{doc.items.map((row,index)=><div className="recap-repeat-row" key={row.id??index}><input aria-label="Item name" placeholder="Item name" maxLength={200} value={row.itemName} onChange={e=>setDoc(c=>({...c,items:patch(c.items,index,{itemName:e.target.value})}))}/><input aria-label="Brand" placeholder="Brand" value={row.brand??""} onChange={e=>setDoc(c=>({...c,items:patch(c.items,index,{brand:e.target.value})}))}/><input aria-label="Size" placeholder="Size" value={row.size??""} onChange={e=>setDoc(c=>({...c,items:patch(c.items,index,{size:e.target.value})}))}/><input aria-label="Color" placeholder="Color" value={row.color??""} onChange={e=>setDoc(c=>({...c,items:patch(c.items,index,{color:e.target.value})}))}/><select aria-label="Disposition" value={row.disposition} onChange={e=>setDoc(c=>({...c,items:patch(c.items,index,{disposition:e.target.value as Item["disposition"]})}))}><option value="purchased">Purchased</option><option value="considered">Considered</option></select><label><input type="checkbox" checked={row.clientFacing} onChange={e=>setDoc(c=>({...c,items:patch(c.items,index,{clientFacing:e.target.checked})}))}/> Client-facing</label><button type="button" onClick={()=>setDoc(c=>({...c,items:c.items.filter((_,i)=>i!==index)}))}>Remove</button></div>)}<button type="button" onClick={()=>setDoc(c=>({...c,items:[...c.items,{itemName:"",brand:null,size:null,color:null,category:null,note:null,disposition:"purchased",clientFacing:true}]}))}>Add item</button></fieldset>
  <fieldset><legend>Outfit Formulas</legend>{doc.formulas.length>4&&<p className="admin-warning">The client-facing recommendation is 4 formulas; up to 8 may be saved internally.</p>}{doc.formulas.map((row,index)=><div className={`recap-repeat-row ${index<4?"client-emphasis":""}`} key={row.id??index}><input aria-label="Outfit formula" maxLength={200} placeholder="Formula" value={row.formulaText} onChange={e=>setDoc(c=>({...c,formulas:patch(c.formulas,index,{formulaText:e.target.value})}))}/><textarea aria-label="Formula explanation" maxLength={500} placeholder="Explanation" value={row.explanation??""} onChange={e=>setDoc(c=>({...c,formulas:patch(c.formulas,index,{explanation:e.target.value})}))}/><button type="button" onClick={()=>setDoc(c=>({...c,formulas:c.formulas.filter((_,i)=>i!==index)}))}>Remove</button></div>)}<button type="button" disabled={doc.formulas.length>=8} onClick={()=>setDoc(c=>({...c,formulas:[...c.formulas,{formulaText:"",explanation:null}]}))}>Add formula</button></fieldset>
  <fieldset><legend>Next Priorities</legend>{doc.priorities.map((row,index)=><div className="recap-repeat-row" key={row.id??index}><input aria-label="Priority" maxLength={200} value={row.priorityText} onChange={e=>setDoc(c=>({...c,priorities:patch(c.priorities,index,{priorityText:e.target.value})}))}/><select aria-label="Priority status" value={row.status} onChange={e=>setDoc(c=>({...c,priorities:patch(c.priorities,index,{status:e.target.value})}))}><option value="open">Open</option><option value="in_progress">In progress</option><option value="completed">Completed</option><option value="no_longer_needed">No longer needed</option></select><label><input type="checkbox" checked={row.clientFacing} onChange={e=>setDoc(c=>({...c,priorities:patch(c.priorities,index,{clientFacing:e.target.checked})}))}/> Client-facing</label><button type="button" disabled={index===0} onClick={()=>setDoc(c=>{const rows=[...c.priorities];[rows[index-1],rows[index]]=[rows[index],rows[index-1]];return{...c,priorities:rows};})}>Up</button><button type="button" disabled={index===doc.priorities.length-1} onClick={()=>setDoc(c=>{const rows=[...c.priorities];[rows[index],rows[index+1]]=[rows[index+1],rows[index]];return{...c,priorities:rows};})}>Down</button><button type="button" onClick={()=>setDoc(c=>({...c,priorities:c.priorities.filter((_,i)=>i!==index)}))}>Remove</button></div>)}<button type="button" onClick={()=>setDoc(c=>({...c,priorities:[...c.priorities,{category:null,priorityText:"",status:"open",clientFacing:true}]}))}>Add priority</button></fieldset>
  <label>A Note for the Client<textarea maxLength={400} value={doc.recap.kaylaNote??""} onChange={e=>scalar({kaylaNote:e.target.value})}/><small>{400-(doc.recap.kaylaNote?.length??0)} of 400 characters remaining</small></label>
  <fieldset><legend>Recommended Next Styling Moment</legend><label>Service type<input value={doc.recap.nextMomentServiceType??""} onChange={e=>scalar({nextMomentServiceType:e.target.value})}/></label><label>Timing<input value={doc.recap.nextMomentTiming??""} onChange={e=>scalar({nextMomentTiming:e.target.value})}/></label><label>Reason<textarea value={doc.recap.nextMomentReason??""} onChange={e=>scalar({nextMomentReason:e.target.value})}/></label><label><input type="checkbox" checked={doc.recap.nextMomentBookingCtaEnabled} onChange={e=>scalar({nextMomentBookingCtaEnabled:e.target.checked})}/> Enable booking CTA</label></fieldset>
  <label className="private-recap-note">Private Follow-Up Note <strong>Internal only</strong><textarea maxLength={2000} value={doc.recap.privateFollowUpNote??""} onChange={e=>scalar({privateFollowUpNote:e.target.value})}/></label>
  {message&&<p role="status">{message}</p>}<div><button className="primary-button" disabled={saving} onClick={()=>void save(doc.recap.status==="not_started"?"draft":doc.recap.status)}>Save Draft</button><button disabled={saving} onClick={()=>void save("ready_for_review")}>Mark Ready for Review</button><a className="button" href={`/admin/recap-preview/${bookingId}`}>Preview Style Summary</a></div>
 </div>;
}
