export async function sha256(value: string) { const digest = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(value)); return Array.from(new Uint8Array(digest), (b) => b.toString(16).padStart(2, "0")).join(""); }
export async function hashPrivateToken(rawToken: string) { return sha256(rawToken); }
export function randomPrivateToken() { const bytes = crypto.getRandomValues(new Uint8Array(32)); let binary = ""; for (const byte of bytes) binary += String.fromCharCode(byte); return btoa(binary).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/g, ""); }
export function randomPublicReference() { const value = crypto.getRandomValues(new Uint32Array(1))[0] % 10000; return `SWK-${String(value).padStart(4, "0")}`; }

export type EncryptedPrivateToken = { tokenCiphertext: string; tokenIv: string; tokenAuthTag: string };
const encoder = new TextEncoder();
const decoder = new TextDecoder();
function encodeBase64Url(bytes: Uint8Array) { let binary = ""; for (const byte of bytes) binary += String.fromCharCode(byte); return btoa(binary).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/g, ""); }
function decodeBase64Url(value: string) { if (!/^[A-Za-z0-9_-]+$/.test(value)) throw new Error("Invalid base64url value."); const padded = value.replace(/-/g, "+").replace(/_/g, "/") + "=".repeat((4-value.length%4)%4); const binary = atob(padded); return Uint8Array.from(binary, character => character.charCodeAt(0)); }
async function privateTokenKey(encodedKey: string, usage: KeyUsage) { const bytes = decodeBase64Url(encodedKey); if (bytes.byteLength !== 32) throw new Error("STYLE_SUMMARY_TOKEN_ENCRYPTION_KEY must be a base64url-encoded 256-bit key."); return crypto.subtle.importKey("raw", bytes, "AES-GCM", false, [usage]); }
export async function encryptPrivateToken(rawToken: string, encodedKey: string): Promise<EncryptedPrivateToken> { const iv = crypto.getRandomValues(new Uint8Array(12)); const encrypted = new Uint8Array(await crypto.subtle.encrypt({ name: "AES-GCM", iv, tagLength: 128 }, await privateTokenKey(encodedKey, "encrypt"), encoder.encode(rawToken))); const tag = encrypted.slice(-16); return { tokenCiphertext: encodeBase64Url(encrypted.slice(0,-16)), tokenIv: encodeBase64Url(iv), tokenAuthTag: encodeBase64Url(tag) }; }
export async function decryptPrivateToken(value: EncryptedPrivateToken, encodedKey: string) { const iv=decodeBase64Url(value.tokenIv), ciphertext=decodeBase64Url(value.tokenCiphertext), tag=decodeBase64Url(value.tokenAuthTag); if(iv.byteLength!==12||tag.byteLength!==16)throw new Error("Invalid encrypted private token fields."); const combined=new Uint8Array(ciphertext.byteLength+tag.byteLength); combined.set(ciphertext); combined.set(tag,ciphertext.byteLength); return decoder.decode(await crypto.subtle.decrypt({name:"AES-GCM",iv,tagLength:128},await privateTokenKey(encodedKey,"decrypt"),combined)); }
