import { ApiError, validation } from "./http";

export const STYLE_PROFILE_TOKEN_TTL_MS=30*24*60*60*1000;
export const PROFILE_SCHEMA_VERSION=1;
export const PROFILE_TYPES=new Set(["under_40","over_40","womens_event","mens_styling","mens_event"]);
export type ProfileQuestion={key:string;label:string;kind:"text"|"long_text"|"link"|"date"|"single"|"multi"|"visual_single"|"visual_multi";required?:boolean;optional?:boolean;maxSelections?:number;options?:string[];placeholder?:string;returningOnly?:boolean;showUnless?:{key:string;value:string};};
export type ProfileSection={title:string;intro:string;questions:ProfileQuestion[]};
const q=(key:string,label:string,kind:ProfileQuestion["kind"],extra:Omit<ProfileQuestion,"key"|"label"|"kind">={}):ProfileQuestion=>({key,label,kind,...extra});
const shapes=["Hourglass","Pear","Apple","Rectangle","Inverted Triangle","Not sure"],topFits=["More fitted","Relaxed","Oversized","No preference"],pantCuts=["Skinny","Straight","Bootcut","Boyfriend / Girlfriend","Wide Leg","Open to trying different cuts","Other"];
const commonFinal=[q("changed_since_last_visit","Have any of your sizes, preferences, or style changed since the last time we met?","single",{options:["Yes","No","Maybe"],returningOnly:true}),q("additional_notes","Is there anything else you'd like me to know before our appointment?","long_text",{optional:true})];
export const PROFILE_SCHEMAS:Record<string,ProfileSection[]>={
 under_40:[
  {title:"What you're looking for",intro:"This gives me a feel for the life your clothes need to support.",questions:[q("shopping_for","What are you shopping for?","multi",{required:true,maxSelections:3,options:["Everyday Outfits","Workwear","Event","Vacation","Closet Reset","Other"]}),q("shopping_for_details","Tell me a little more about what you need.","long_text",{required:true}),q("top_styles","Pick up to 3 styles that feel most like you.","visual_multi",{required:true,maxSelections:3,options:["Minimal","Statement","Sporty","Casual","Trendy","Feminine","Other"]}),q("inspiration","Do you have inspiration photos, a Pinterest board, or colors you want me to see?","link",{optional:true}),q("feel_best_in","What styles, colors, or silhouettes do you feel best in?","long_text",{required:true}),q("avoid","Are there any styles, colors, or pieces you do not want to wear?","long_text",{required:true,placeholder:"Nothing specific is a valid answer."}),q("metal_preference","Which metal do you usually prefer?","single",{optional:true,options:["Gold","Silver","Both","No preference"]})]},
  {title:"Fit and comfort",intro:"There are no right answers—this helps me pull better options.",questions:[q("body_shape","Which illustration most closely resembles your shape?","visual_single",{required:true,options:shapes}),q("frustration","What's been most frustrating about getting dressed lately?","single",{required:true,options:["Nothing to wear","Outfits don't feel put together","Struggle with fit","Don't know how to style what I have","Closet feels outdated","Other"]}),q("difficulty_fitting","Which areas are usually most difficult to fit?","multi",{required:true,options:["Midsection","Chest","Hips","Arms","Length","No consistent difficulty","Other"]}),q("shop_sizing","Which sizing department usually works best for you?","single",{required:true,options:["Regular","Petite","Plus","Tall / Long","Not sure","Other"]}),q("fabric_preference","What tends to feel best on your body?","single",{required:true,options:["Structured","Stretchy","A mix","Not sure / open to both"]})]},
  {title:"Sizes and silhouettes",intro:"Share your best estimate for a useful starting point.",questions:[q("top_size","What top size do you usually wear?","single",{required:true,options:["XS","S","M","L","XL","XXL","Not sure","Other"]}),q("top_fit_preference","How do you usually like your tops to fit?","visual_multi",{required:true,options:topFits}),q("pant_size","What pant size do you usually wear?","text",{required:true,placeholder:"00/1–16/17, Not sure, or Other"}),q("pant_cut_preference","Which pant cuts do you prefer?","visual_multi",{required:true,options:pantCuts}),q("dress_size","What dress size do you usually wear?","text",{required:true,placeholder:"Size, Not sure, N/A, or Other"}),q("dress_styles","Which dress styles do you usually feel best in?","visual_multi",{options:["Bodycon","Shift","A-Line","Wrap","Shirt","Slip","Maxi","Not sure","Other"],showUnless:{key:"dress_size",value:"N/A"}}),q("shoe_size","What shoe size do you usually wear?","text",{required:true}),q("bra_size","What bra size do you usually wear, if known?","text",{optional:true})]},
  {title:"Final details",intro:"A last chance to share anything helpful.",questions:commonFinal}
 ],
 over_40:[
  {title:"What you're looking for",intro:"Tell me what your wardrobe needs to support.",questions:[q("shopping_for","What are you shopping for?","multi",{required:true,maxSelections:3,options:["Everyday","Business Casual","Workwear","Date Night","Closet Update","Vacation","Other"]}),q("shopping_for_details","Tell me a little more about what you're looking for.","long_text",{required:true}),q("top_styles","Pick up to 3 styles that feel most like you.","visual_multi",{required:true,maxSelections:3,options:["Classic","Sporty","Bold","Minimal","Trendy","Athletic","Casual","Other"]}),q("inspiration","Do you have inspiration photos, a Pinterest board, or colors you want me to see?","link",{optional:true}),q("feel_best_in","What styles, colors, or pieces do you feel best in?","long_text",{required:true}),q("avoid","Are there any styles, colors, or pieces you do not want to wear?","long_text",{required:true}),q("frustration","What's been most frustrating about getting dressed lately?","single",{required:true,options:["Nothing to wear","Closet feels outdated","Struggle with fit","Don't know how to put outfits together","Size has changed","Other"]}),q("metal_preference","Which metal do you usually prefer?","single",{optional:true,options:["Gold","Silver","Both","No preference","Other"]})]},
  {title:"Fit and comfort",intro:"This helps me choose comfortable starting options.",questions:[q("body_shape","Which illustration most closely resembles your shape?","visual_single",{required:true,options:shapes}),q("difficulty_fitting","Which areas are usually most difficult to fit?","multi",{required:true,options:["Midsection","Chest","Hips","Arms","Length","General sizing","No consistent difficulty","Other"]}),q("shop_sizing","Which sizing department usually works best for you?","single",{required:true,options:["Regular","Petite","Plus","Tall / Long","Not sure","Other"]}),q("fabric_preference","What tends to feel best on your body?","single",{required:true,options:["Structured","Stretchy","A mix","Not sure / open to both","Other"]})]},
  {title:"Sizes and silhouettes",intro:"Flexible estimates are welcome.",questions:[q("top_size","What top size do you usually wear?","text",{required:true}),q("top_fit_preference","How do you usually like your tops to fit?","visual_multi",{required:true,options:topFits}),q("neckline_preference","Do you have a preferred neckline?","single",{optional:true,options:["Scoop","Round","V-Neck","Higher V-Neck","Boat","No preference","Other"]}),q("pant_size","What pant size do you usually wear?","text",{required:true}),q("pant_cut_preference","Which pant cuts do you prefer?","visual_multi",{required:true,options:pantCuts}),q("dress_size","What dress size do you usually wear?","text",{required:true,placeholder:"Size, N/A, or Not sure"}),q("dress_styles","Which dress styles do you usually feel best in?","visual_multi",{options:["Bodycon","Shift","A-Line","Wrap","Shirt","Slip","Maxi","Not sure","Other"],showUnless:{key:"dress_size",value:"N/A"}}),q("shoe_size","What shoe size do you usually wear?","text",{required:true}),q("bra_size","What bra size do you usually wear, if known?","text",{optional:true})]},
  {title:"Final details",intro:"A last chance to share anything helpful.",questions:commonFinal}
 ],
 womens_event:[
  {title:"Your event",intro:"Start with the occasion and its dress expectations.",questions:[q("event_type","What type of event are you shopping for?","single",{required:true,options:["Wedding Guest","Wedding Party","Gala / Formal Event","Cocktail / Holiday Party","School Dance","Other"]}),q("event_date","When is the event?","date",{required:true}),q("event_location","Where is the event taking place? Is it indoors or outdoors?","long_text",{required:true}),q("dress_code","What is the dress code, if you know it?","visual_single",{required:true,options:["Casual","Dressy Casual","Business / Professional","Cocktail","Semi-Formal","Formal / Black Tie","Themed Event","Not sure","Other"]}),q("event_details","Tell me a little more about the event.","long_text",{optional:true}),q("required_colors_themes","Are there required colors, themes, or dress guidelines?","long_text",{optional:true})]},
  {title:"Styling goals",intro:"Choose the direction you want the event look to take.",questions:[q("top_event_styles","Pick up to 3 styles for your event look.","visual_multi",{required:true,maxSelections:3,options:["Classic Elegant","Romantic Feminine","Modern Minimal","Bold Statement","Trendy / Fashion Forward","Soft Glam","Polished Professional","Glam","Other"]}),q("inspiration","Do you have inspiration photos, a Pinterest board, or colors you want me to see?","link",{optional:true}),q("feel_best_in","What styles, colors, or silhouettes do you feel best in?","long_text",{required:true}),q("avoid","Are there any styles, colors, or pieces you do not want to wear?","long_text",{required:true}),q("metal_preference","Which metal do you usually prefer?","single",{optional:true,options:["Gold","Silver","Both","No preference","Other"]})]},
  {title:"Outfit preferences and fit",intro:"This helps narrow the right event options.",questions:[q("body_shape","Which illustration most closely resembles your shape?","visual_single",{required:true,options:shapes}),q("outfit_types_open_to","Which outfit types are you open to?","multi",{required:true,options:["Dress","Jumpsuit","Skirt Outfit","Pants Outfit","Suit / Blazer Look","Not sure","Other"]}),q("coverage_preference","What level of coverage do you prefer?","multi",{required:true,options:["Sleeveless is fine","Short sleeves","Longer sleeves","Minimal cleavage","Leg coverage","No preference","Other"]}),q("fabric_preference","What tends to feel best on your body?","multi",{required:true,options:["Structured","Stretchy","Flowy","A mix","Not sure","Other"]}),q("difficulty_fitting","Which areas are usually most difficult to fit?","multi",{required:true,options:["Midsection","Chest","Hips","Arms","Length","No consistent difficulty","Other"]}),q("shop_sizing","Which sizing department usually works best for you?","single",{required:true,options:["Regular","Petite","Plus","Tall / Long","Not sure","Other"]})]},
  {title:"Sizes",intro:"Provide your best estimate for a starting point.",questions:[q("top_size","What top size do you usually wear?","text",{required:true}),q("top_fit_preference","How do you usually like your tops to fit?","visual_multi",{required:true,options:topFits}),q("pant_size","What pant size do you usually wear?","text",{required:true}),q("pant_cut_preference","Which pant cuts do you prefer?","visual_multi",{required:true,options:["Skinny","Straight","Bootcut","Cropped","Wide Leg","Open to trying different cuts","Other"]}),q("dress_size","What dress size do you usually wear?","text",{required:true}),q("dress_styles","Which dress styles do you usually feel best in?","visual_multi",{options:["Bodycon","Fit and Flare","A-Line","Wrap","Slip","Mermaid Gown","Ballgown","Column","Not sure","Other"],showUnless:{key:"dress_size",value:"N/A"}}),q("shoe_size","What shoe size do you usually wear?","text",{required:true}),q("shoe_type_preference","Which shoe types are you open to?","multi",{required:true,options:["High Heels 3+ inches","Low Heels 2–3 inches","Flats","Dressy Sandals","Boots / Booties","Dressy Sneakers","Not sure","Other"]}),q("bra_size","What bra size do you usually wear, if known?","text",{optional:true})]},
  {title:"Finishing touches",intro:"A few final event details.",questions:[q("additional_help_interested","What additional styling help would interest you?","multi",{optional:true,options:["Jewelry","Handbag / Clutch","Shapewear","Bra","Fragrance","Beauty","None","Other"]}),q("shopping_for_others","Are you shopping for anyone else for this event?","single",{required:true,options:["No","Partner","Family member","Friend","Group","Other"]}),q("additional_notes","Is there anything else you'd like me to know before our appointment?","long_text",{optional:true})]}
 ],
 mens_styling:[
  {title:"What you're looking for",intro:"Tell me what your clothes need to support.",questions:[q("shopping_for","What are you shopping for?","multi",{required:true,maxSelections:3,options:["Everyday","Business Casual","Workwear","Date Night","Closet Update","Vacation","Other"]}),q("shopping_for_details","Tell me a little more about what you're looking for.","long_text",{required:true}),q("top_styles","Pick up to 3 styles that feel most like you.","visual_multi",{required:true,maxSelections:3,options:["Casual","Modern","Trendy","Business Professional","Rugged","Athletic","Relaxed","Other"]}),q("typical_week","What does a typical week look like for you?","single",{required:true,options:["Mostly Casual","Business Casual","Professional Office","Active / Outdoors","Frequent Travel","Mix","Other"]}),q("feel_best_in","Are there styles, colors, or pieces you feel best in?","long_text",{required:true}),q("avoid","Are there styles, colors, or pieces you do not want to wear?","long_text",{required:true})]},
  {title:"Fit and sizes",intro:"Flexible estimates are welcome.",questions:[q("shop_sizing","Which sizing department usually works best for you?","single",{required:true,options:["Regular","Big & Tall","Athletic / Modern","Not sure","Other"]}),q("fit_preference","What fit do you usually prefer?","visual_single",{required:true,options:["Slim","Tailored","Modern","Classic","Relaxed","Not sure","Other"]}),q("shirt_size","What shirt size do you usually wear?","text",{required:true}),q("dress_shirt_size","What dress-shirt size do you usually wear?","text",{required:true,placeholder:"For example: 16 32/33, or Not sure"}),q("jacket_size","What jacket size do you usually wear?","text",{required:true,placeholder:"For example: 40R, or Not sure"}),q("pant_size","What pant size do you usually wear?","text",{required:true,placeholder:"For example: 36/34, or Not sure"}),q("shoe_size","What shoe size do you usually wear?","text",{required:true}),q("additional_notes","Is there anything else you'd like me to know before our appointment?","long_text",{optional:true})]}
 ],
 mens_event:[
  {title:"Your event",intro:"Start with the occasion and dress expectations.",questions:[q("event_type","What type of event are you shopping for?","single",{required:true,options:["Wedding Guest","Wedding Party","Business","Gala / Formal","School Dance","Other"]}),q("event_date","When is the event?","date",{required:true}),q("event_location","Where is the event taking place? Is it indoors or outdoors?","long_text",{required:true}),q("dress_code","What is the dress code, if you know it?","visual_single",{required:true,options:["Casual","Dressy Casual","Business / Professional","Semi-Formal","Formal / Black Tie","Not sure","Other"]}),q("required_colors_themes","Are there required colors, themes, or event guidelines?","long_text",{optional:true})]},
  {title:"Style and outfit direction",intro:"Choose the direction for your event look.",questions:[q("top_event_styles","Pick up to 3 styles for your event look.","visual_multi",{required:true,maxSelections:3,options:["Classic","Modern","Trendy","Casual","Polished","Bold","Other"]}),q("avoid","Are there styles, colors, or pieces you do not want to wear?","long_text",{required:true}),q("outfit_types_open_to","Which outfit types are you open to?","multi",{required:true,options:["Polo","Dress Shirt","Sports Coat","Traditional Suit","3-Piece Suit","Tuxedo","Not sure","Other"]}),q("fit_preference","What fit do you usually prefer?","visual_single",{required:true,options:["Slim","Tailored","Modern","Classic","Relaxed","Not sure","Other"]}),q("shop_sizing","Which sizing department usually works best for you?","single",{required:true,options:["Regular","Big & Tall","Athletic / Modern","Not sure","Other"]})]},
  {title:"Sizes",intro:"Provide your best estimate for a starting point.",questions:[q("shirt_size","What shirt size do you usually wear?","text",{required:true}),q("dress_shirt_size","What dress-shirt size do you usually wear?","text",{required:true,placeholder:"For example: 16 32/33, or Not sure"}),q("jacket_size","What jacket size do you usually wear?","text",{required:true,placeholder:"For example: 40R, or Not sure"}),q("pant_size","What pant size do you usually wear?","text",{required:true,placeholder:"For example: 36/34, or Not sure"}),q("shoe_size","What shoe size do you usually wear?","text",{required:true}),q("additional_notes","Is there anything else you'd like me to know before our appointment?","long_text",{optional:true})]}
 ]
};

export function validateProfileDraft(value:unknown,submit=false,profileType="under_40",returningClient=false){
 if(!value||typeof value!=="object"||Array.isArray(value))throw validation("answers","Profile answers must be an object.");const answers=value as Record<string,unknown>,schema=PROFILE_SCHEMAS[profileType];if(!schema)throw new ApiError(422,"INVALID_PROFILE_TYPE","This Style Profile type is not supported.");if(JSON.stringify(answers).length>32000)throw new ApiError(413,"PROFILE_TOO_LARGE","The Style Profile is too large.");const questions=schema.flatMap(section=>section.questions),byKey=new Map(questions.map(question=>[question.key,question]));for(const key of Object.keys(answers))if(!byKey.has(key))throw validation(`answers.${key}`,"This profile field is not recognized.");for(const question of questions){if(question.returningOnly&&!returningClient)continue;if(question.showUnless&&answers[question.showUnless.key]===question.showUnless.value)continue;const value=answers[question.key];if(value===undefined||value===null||value===""||(Array.isArray(value)&&!value.length)){if(submit&&question.required)throw validation(`answers.${question.key}`,"This field is required.");continue;}if(question.kind==="multi"||question.kind==="visual_multi"){if(!Array.isArray(value)||value.some(item=>typeof item!=="string"||!item.trim()||item.length>120))throw validation(`answers.${question.key}`,"Choose valid options.");if(question.maxSelections&&value.length>question.maxSelections)throw validation(`answers.${question.key}`,`Choose up to ${question.maxSelections} options.`);if(question.options&&value.some(item=>!question.options!.includes(item)))throw validation(`answers.${question.key}`,"Choose from the available options.");}else{if(typeof value!=="string"||value.length>2000)throw validation(`answers.${question.key}`,"This value is invalid or too long.");if((question.kind==="single"||question.kind==="visual_single")&&question.options&&!question.options.includes(value))throw validation(`answers.${question.key}`,"Choose from the available options.");if(question.kind==="date"&&!/^\d{4}-\d{2}-\d{2}$/.test(value))throw validation(`answers.${question.key}`,"Choose a valid date.");}}
 return answers;
}
