export type StyleSummaryEmailData={firstName:string;styleSummaryUrl:string};
const escape=(value:string)=>value.replace(/[&<>"']/g,character=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[character]!);

export function renderStyleSummaryEmail(data:StyleSummaryEmailData) {
  const firstName=escape(data.firstName.trim()||"there"),url=escape(data.styleSummaryUrl);
  const subject="Your Style Summary is ready";
  const html=`<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"></head><body style="margin:0;padding:0;background:#eee7e3;color:#171515;"><table role="presentation" width="100%" border="0" cellspacing="0" cellpadding="0" bgcolor="#eee7e3" style="width:100%;background:#eee7e3;"><tr><td align="center" style="padding:24px 10px;"><table role="presentation" width="640" border="0" cellspacing="0" cellpadding="0" bgcolor="#fffdfb" style="width:100%;max-width:640px;background:#fffdfb;border:1px solid #eaded8;"><tr><td align="center" bgcolor="#030303" style="padding:16px 20px;background:#030303;"><img src="https://stylewithkayla.com/images/stylewithkayla_logo_white_transparent.png" width="220" alt="Style with Kayla" style="display:block;width:220px;max-width:100%;height:auto;margin:0 auto;border:0;"></td></tr><tr><td style="padding:38px 34px;"><p style="margin:0 0 12px;color:#b94464;font-family:Arial,Helvetica,sans-serif;font-size:12px;font-weight:700;letter-spacing:3px;text-transform:uppercase;">Your appointment recap</p><h1 style="margin:0 0 24px;color:#171515;font-family:Georgia,'Times New Roman',serif;font-size:38px;line-height:44px;font-weight:400;">Your Style Summary is ready</h1><p style="margin:0 0 16px;color:#514a48;font-family:Arial,Helvetica,sans-serif;font-size:15px;line-height:24px;">Hi ${firstName},</p><p style="margin:0 0 24px;color:#514a48;font-family:Arial,Helvetica,sans-serif;font-size:15px;line-height:24px;">Thank you again for styling with me. I pulled together your Style Summary with the pieces, outfit ideas, and styling notes we discussed during your appointment.</p><table role="presentation" border="0" cellspacing="0" cellpadding="0"><tr><td bgcolor="#b94464" style="border-radius:999px;text-align:center;"><a href="${url}" style="display:inline-block;padding:14px 24px;color:#ffffff;font-family:Georgia,'Times New Roman',serif;font-size:18px;line-height:22px;text-decoration:none;">View Your Style Summary</a></td></tr></table><p style="margin:26px 0 20px;color:#514a48;font-family:Arial,Helvetica,sans-serif;font-size:15px;line-height:24px;">I hope it makes getting dressed a little easier. If you have any questions, just reply to this email.</p><p style="margin:0 0 10px;color:#171515;font-family:Georgia,'Times New Roman',serif;font-size:18px;line-height:26px;">Kayla</p><img src="https://stylewithkayla.com/images/stylewithkayla_logo.png" width="160" alt="Style with Kayla" style="display:block;width:160px;max-width:100%;height:auto;border:0;"></td></tr><tr><td align="center" bgcolor="#030303" style="padding:20px;background:#030303;color:#ffffff;font-family:Arial,Helvetica,sans-serif;font-size:10px;line-height:16px;letter-spacing:1px;text-transform:uppercase;">© 2026 Style with Kayla &nbsp;|&nbsp; Personal Stylist at Macy’s</td></tr></table></td></tr></table></body></html>`;
  const text=`Hi ${data.firstName.trim()||"there"},\n\nThank you again for styling with me. I pulled together your Style Summary with the pieces, outfit ideas, and styling notes we discussed during your appointment.\n\nView Your Style Summary:\n${data.styleSummaryUrl}\n\nI hope it makes getting dressed a little easier. If you have any questions, just reply to this email.\n\n— Kayla\nPersonal Stylist`;
  return {subject,html,text};
}
