import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
import { DatabaseSync } from "node:sqlite";

const migration = await readFile(new URL("../drizzle/0000_silent_ser_duncan.sql",import.meta.url),"utf8");
function database(){const db=new DatabaseSync(":memory:");for(const statement of migration.split("--> statement-breakpoint").map(value=>value.trim()).filter(Boolean))db.exec(statement);return db;}

test("D1 schema rejects a second active hold for the same booking",()=>{const db=database(),now=Date.now(),service=db.prepare("SELECT id FROM services ORDER BY sort_order LIMIT 1").get();db.prepare("INSERT INTO clients(id,full_name,email,normalized_email,phone,created_at,updated_at) VALUES(?,?,?,?,?,?,?)").run("client-1","Test Client","test@example.com","test@example.com","2085550100",now,now);db.prepare("INSERT INTO bookings(id,public_reference,client_id,service_id,status,requested_start_at,requested_end_at,returning_client,how_heard,privacy_policy_version,privacy_acknowledged_at,pending_since,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)").run("booking-1","SWK-TEST1","client-1",service.id,"pending",now+86400000,now+90000000,0,"Referral","test",now,now,now,now);db.prepare("INSERT INTO booking_holds(id,booking_id,kind,starts_at,ends_at,active,created_at) VALUES(?,?,?,?,?,?,?)").run("hold-1","booking-1","requested",now+86400000,now+90000000,1,now);assert.throws(()=>db.prepare("INSERT INTO booking_holds(id,booking_id,kind,starts_at,ends_at,active,created_at) VALUES(?,?,?,?,?,?,?)").run("hold-2","booking-1","proposed",now+90000000,now+93600000,1,now),/UNIQUE constraint failed/);});

test("overlap guard permits one pending request and rejects the race loser",()=>{const db=database(),now=Date.now(),service=db.prepare("SELECT id FROM services ORDER BY sort_order LIMIT 1").get(),start=now+86400000,end=start+3600000;for(const id of["a","b"])db.prepare("INSERT INTO clients(id,full_name,email,normalized_email,phone,created_at,updated_at) VALUES(?,?,?,?,?,?,?)").run(`client-${id}`,`Client ${id}`,`${id}@example.com`,`${id}@example.com`,"2085550100",now,now);const insert=db.prepare("INSERT INTO bookings(id,public_reference,client_id,service_id,status,requested_start_at,requested_end_at,returning_client,how_heard,privacy_policy_version,privacy_acknowledged_at,pending_since,created_at,updated_at) SELECT ?,?,?,?,?,?,?,?,?,?,?,?,?,? WHERE NOT EXISTS(SELECT 1 FROM booking_holds h WHERE h.active=1 AND h.starts_at<? AND h.ends_at>?)");assert.equal(insert.run("booking-a","SWK-RACEA","client-a",service.id,"pending",start,end,0,"Referral","test",now,now,now,now,end,start).changes,1);db.prepare("INSERT INTO booking_holds(id,booking_id,kind,starts_at,ends_at,active,created_at) VALUES(?,?,?,?,?,?,?)").run("hold-a","booking-a","requested",start,end,1,now);assert.equal(insert.run("booking-b","SWK-RACEB","client-b",service.id,"pending",start,end,0,"Referral","test",now,now,now,now,end,start).changes,0);assert.equal(db.prepare("SELECT COUNT(*) AS count FROM bookings").get().count,1);});

test("expired-token revocation does not revoke a future private link",()=>{const db=database(),now=Date.now(),service=db.prepare("SELECT id FROM services ORDER BY sort_order LIMIT 1").get();db.prepare("INSERT INTO clients(id,full_name,email,normalized_email,phone,created_at,updated_at) VALUES('client','Test','test@example.com','test@example.com','2085550100',?,?)").run(now,now);db.prepare("INSERT INTO bookings(id,public_reference,client_id,service_id,status,requested_start_at,requested_end_at,returning_client,how_heard,privacy_policy_version,privacy_acknowledged_at,pending_since,created_at,updated_at) VALUES('booking','SWK-TOKEN','client',?,'confirmed',?,?,0,'Referral','test',?,?,?,?)").run(service.id,now,now+3600000,now,now,now,now);const insert=db.prepare("INSERT INTO private_access_tokens(id,booking_id,purpose,token_hash,expires_at,created_at) VALUES(?,?,?,?,?,?)");insert.run("expired","booking","style_profile","expired-hash",now-1,now);insert.run("future","booking","style_profile","future-hash",now+86400000,now);db.prepare("UPDATE private_access_tokens SET revoked_at=? WHERE revoked_at IS NULL AND expires_at<=?").run(now,now);assert.equal(db.prepare("SELECT revoked_at FROM private_access_tokens WHERE id='expired'").get().revoked_at,now);assert.equal(db.prepare("SELECT revoked_at FROM private_access_tokens WHERE id='future'").get().revoked_at,null);});

test("pending booking can move through confirmation, completion, and privacy erasure",()=>{const db=database(),now=Date.now(),start=now+86400000,end=start+3600000,service=db.prepare("SELECT id FROM services ORDER BY sort_order LIMIT 1").get();db.exec("PRAGMA foreign_keys=ON");db.prepare("INSERT INTO clients(id,full_name,email,normalized_email,phone,created_at,updated_at) VALUES('lifecycle-client','Lifecycle Client','lifecycle@example.com','lifecycle@example.com','2085550100',?,?)").run(now,now);db.prepare("INSERT INTO bookings(id,public_reference,client_id,service_id,status,requested_start_at,requested_end_at,returning_client,how_heard,privacy_policy_version,privacy_acknowledged_at,pending_since,created_at,updated_at) VALUES('lifecycle-booking','SWK-LIFE','lifecycle-client',?,'pending',?,?,0,'Referral','test',?,?,?,?)").run(service.id,start,end,now,now,now,now);db.prepare("INSERT INTO booking_holds(id,booking_id,kind,starts_at,ends_at,active,created_at) VALUES('lifecycle-hold','lifecycle-booking','requested',?,?,1,?)").run(start,end,now);db.prepare("UPDATE bookings SET status='confirmed',confirmed_start_at=?,confirmed_end_at=?,confirmed_at=? WHERE id='lifecycle-booking' AND status='pending'").run(start,end,now);db.prepare("UPDATE booking_holds SET kind='confirmed' WHERE id='lifecycle-hold'").run();assert.equal(db.prepare("SELECT status FROM bookings WHERE id='lifecycle-booking'").get().status,"confirmed");const retention=Date.UTC(2028,6,14);db.prepare("UPDATE bookings SET status='completed',completed_at=? WHERE id='lifecycle-booking' AND status='confirmed'").run(now);db.prepare("UPDATE booking_holds SET active=0,released_at=? WHERE id='lifecycle-hold'").run(now);db.prepare("UPDATE clients SET last_completed_appointment_at=?,retention_delete_after=? WHERE id='lifecycle-client'").run(now,retention);assert.equal(db.prepare("SELECT retention_delete_after FROM clients WHERE id='lifecycle-client'").get().retention_delete_after,retention);db.prepare("DELETE FROM bookings WHERE client_id='lifecycle-client'").run();db.prepare("UPDATE clients SET full_name='Deleted client',email='deleted+lifecycle-client@invalid.local',normalized_email='deleted+lifecycle-client@invalid.local',phone='Deleted',retention_delete_after=NULL WHERE id='lifecycle-client'").run();assert.equal(db.prepare("SELECT COUNT(*) AS count FROM bookings WHERE client_id='lifecycle-client'").get().count,0);assert.equal(db.prepare("SELECT full_name FROM clients WHERE id='lifecycle-client'").get().full_name,"Deleted client");});
