import assert from "node:assert/strict";
import test from "node:test";
import { addCalendarYears, assertAdminActionState, type AdminBookingAction } from "../lib/server/booking-policy";
import { PROFILE_SCHEMAS, STYLE_PROFILE_TOKEN_TTL_MS, validateProfileDraft, type ProfileQuestion } from "../lib/server/profile-policy";
import { addDays, zonedLocalToEpoch } from "../lib/server/scheduling";
import { validateAvailabilityRules } from "../lib/server/availability-policy";

test("booking actions accept only approved source states",()=>{const valid:Array<[AdminBookingAction,string]>=[["confirm","pending"],["confirm","change_proposed"],["decline","pending"],["release-hold","change_proposed"],["propose-time","pending"],["cancel","confirmed"],["complete","confirmed"]];for(const [action,status] of valid)assert.doesNotThrow(()=>assertAdminActionState(action,status));for(const action of ["confirm","decline","release-hold","propose-time"] as AdminBookingAction[])assert.throws(()=>assertAdminActionState(action,"confirmed"));assert.throws(()=>assertAdminActionState("complete","pending"));assert.throws(()=>assertAdminActionState("cancel","completed"));});
test("private Style Profile links use the approved 30-day lifetime",()=>{assert.equal(STYLE_PROFILE_TOKEN_TTL_MS,30*24*60*60*1000);});
test("written retention uses two calendar years and handles leap day",()=>{assert.equal(new Date(addCalendarYears(Date.UTC(2026,6,14),2)).toISOString(),"2028-07-14T00:00:00.000Z");assert.equal(new Date(addCalendarYears(Date.UTC(2024,1,29),2)).toISOString(),"2026-02-28T00:00:00.000Z");});
test("Boise routine windows convert correctly across daylight saving time",()=>{assert.equal(new Date(zonedLocalToEpoch("2026-07-16",630,"America/Boise")).toISOString(),"2026-07-16T16:30:00.000Z");assert.equal(new Date(zonedLocalToEpoch("2026-01-15",630,"America/Boise")).toISOString(),"2026-01-15T17:30:00.000Z");assert.equal(addDays("2026-12-31",1),"2027-01-01");});
test("profile validation enforces type-specific limits and required fields",()=>{const valid={shopping_for:["Everyday Outfits"],shopping_for_details:"Work and weekends",top_styles:["Minimal"],feel_best_in:"Blue and clean lines",avoid:"Nothing specific",body_shape:"Not sure",frustration:"Nothing to wear",difficulty_fitting:["No consistent difficulty"],shop_sizing:"Regular",fabric_preference:"A mix",top_size:"M",top_fit_preference:["Relaxed"],pant_size:"8",pant_cut_preference:["Straight"],dress_size:"N/A",shoe_size:"8"};assert.deepEqual(validateProfileDraft(valid,true,"under_40"),valid);assert.throws(()=>validateProfileDraft({...valid,top_styles:["Minimal","Statement","Sporty","Casual"]},false,"under_40"));assert.throws(()=>validateProfileDraft({...valid,shoe_size:""},true,"under_40"));assert.throws(()=>validateProfileDraft({...valid,unknown:"value"},false,"under_40"));});
test("availability rules stay within approved days and never overlap",()=>{const rules=[{weekday:2,startMinute:630,endMinute:810},{weekday:2,startMinute:870,endMinute:1050},{weekday:6,startMinute:630,endMinute:810}];assert.deepEqual(validateAvailabilityRules(rules),rules);assert.throws(()=>validateAvailabilityRules([{weekday:1,startMinute:630,endMinute:810}]));assert.throws(()=>validateAvailabilityRules([{weekday:2,startMinute:630,endMinute:810},{weekday:2,startMinute:800,endMinute:900}]));assert.throws(()=>validateAvailabilityRules([{weekday:2,startMinute:900,endMinute:800}]));});
test("all five approved profile schemas have unique stable keys and can submit",()=>{assert.deepEqual(Object.keys(PROFILE_SCHEMAS).sort(),["mens_event","mens_styling","over_40","under_40","womens_event"]);for(const[type,sections]of Object.entries(PROFILE_SCHEMAS)){const questions=sections.flatMap(section=>section.questions),keys=questions.map(question=>question.key);assert.equal(new Set(keys).size,keys.length,`${type} has duplicate keys`);const answers:Record<string,unknown>={};for(const question of questions.filter(question=>question.required&&!question.returningOnly))answers[question.key]=answerFor(question);assert.doesNotThrow(()=>validateProfileDraft(answers,true,type,false),`${type} should accept its complete required answer set`);}});
function answerFor(question:ProfileQuestion){if(question.kind==="multi"||question.kind==="visual_multi")return[question.options?.[0]||"Example"];if(question.kind==="date")return"2026-09-01";if(question.kind==="single"||question.kind==="visual_single")return question.options?.[0]||"Example";return"Example";}
