import assert from "node:assert/strict";
import test from "node:test";
import { addCalendarYears, assertAdminActionState, type AdminBookingAction } from "../lib/server/booking-policy";
import { STYLE_PROFILE_TOKEN_TTL_MS, validateProfileDraft } from "../lib/server/profile-policy";
import { addDays, zonedLocalToEpoch } from "../lib/server/scheduling";

test("booking actions accept only approved source states",()=>{const valid:Array<[AdminBookingAction,string]>=[["confirm","pending"],["confirm","change_proposed"],["decline","pending"],["release-hold","change_proposed"],["propose-time","pending"],["cancel","confirmed"],["complete","confirmed"]];for(const [action,status] of valid)assert.doesNotThrow(()=>assertAdminActionState(action,status));for(const action of ["confirm","decline","release-hold","propose-time"] as AdminBookingAction[])assert.throws(()=>assertAdminActionState(action,"confirmed"));assert.throws(()=>assertAdminActionState("complete","pending"));assert.throws(()=>assertAdminActionState("cancel","completed"));});
test("private Style Profile links use the approved 30-day lifetime",()=>{assert.equal(STYLE_PROFILE_TOKEN_TTL_MS,30*24*60*60*1000);});
test("written retention uses two calendar years and handles leap day",()=>{assert.equal(new Date(addCalendarYears(Date.UTC(2026,6,14),2)).toISOString(),"2028-07-14T00:00:00.000Z");assert.equal(new Date(addCalendarYears(Date.UTC(2024,1,29),2)).toISOString(),"2026-02-28T00:00:00.000Z");});
test("Boise routine windows convert correctly across daylight saving time",()=>{assert.equal(new Date(zonedLocalToEpoch("2026-07-16",630,"America/Boise")).toISOString(),"2026-07-16T16:30:00.000Z");assert.equal(new Date(zonedLocalToEpoch("2026-01-15",630,"America/Boise")).toISOString(),"2026-01-15T17:30:00.000Z");assert.equal(addDays("2026-12-31",1),"2027-01-01");});
test("profile validation enforces limits and required submission fields",()=>{const valid={shoppingFor:["Everyday Outfits"],styles:["Minimal"],bodyShape:"Not sure",sizes:{top:"M",pant:"8",dress:"8",shoe:"8"}};assert.deepEqual(validateProfileDraft(valid,true),valid);assert.throws(()=>validateProfileDraft({...valid,styles:["a","b","c","d"]}));assert.throws(()=>validateProfileDraft({...valid,sizes:{top:"M"}},true));assert.throws(()=>validateProfileDraft({...valid,unknown:"value"}));});
