"use client";
import { useCallback, useEffect, useState } from "react";

type PrivacyRequest={id:string;kind:"access"|"correction"|"deletion";status:string;requestDetails:string|null;resolutionNote:string|null;requestedAt:string;completedAt:string|null;clientName:string;clientEmail:string;activeBookingCount:number};
type Summary={expiredTokenCount:number;dueClientCount:number;openDataRequestCount:number};
const fmt=(value:string|null)=>value?new Intl.DateTimeFormat("en-US",{timeZone:"America/Boise",dateStyle:"medium",timeStyle:"short"}).format(new Date(value)):"—";

export default function AdminPrivacy({userName,signOutPath}:{userName:string;signOutPath:string}){
  const[requests,setRequests]=useState<PrivacyRequest[]>([]),[summary,setSummary]=useState<Summary|null>(null),[filter,setFilter]=useState("active"),[selected,setSelected]=useState(""),[email,setEmail]=useState(""),[kind,setKind]=useState("access"),[details,setDetails]=useState(""),[note,setNote]=useState(""),[error,setError]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false);
  const current=requests.find(item=>item.id===selected)??null;
  const load=useCallback(async()=>{setError("");try{const[requestsResponse,summaryResponse]=await Promise.all([fetch(`/api/admin/data-requests?status=${filter}`,{cache:"no-store"}),fetch("/api/admin/operations/maintenance",{cache:"no-store"})]),requestsPayload=await requestsResponse.json() as {data?:{requests:PrivacyRequest[]};error?:{message?:string}},summaryPayload=await summaryResponse.json() as {data?:Summary;error?:{message?:string}};if(!requestsResponse.ok)throw new Error(requestsPayload.error?.message);if(!summaryResponse.ok)throw new Error(summaryPayload.error?.message);setRequests(requestsPayload.data!.requests);setSummary(summaryPayload.data!);setSelected(id=>requestsPayload.data!.requests.some(item=>item.id===id)?id:(requestsPayload.data!.requests[0]?.id??""));}catch(e){setError(e instanceof Error?e.message:"Privacy operations could not be loaded.");}},[filter]);
  useEffect(()=>{void Promise.resolve().then(load);},[load]);
  async function createRequest(){setBusy(true);setError("");setNotice("");try{const response=await fetch("/api/admin/data-requests",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({clientEmail:email,kind,requestDetails:details||null})}),payload=await response.json() as {error?:{message?:string}};if(!response.ok)throw new Error(payload.error?.message);setEmail("");setDetails("");setNotice("Privacy request recorded.");await load();}catch(e){setError(e instanceof Error?e.message:"The privacy request could not be recorded.");}finally{setBusy(false);}}
  async function updateRequest(status:"in_progress"|"completed"|"declined"){if(!current)return;if(status==="completed"&&current.kind==="deletion"&&!window.confirm("This permanently removes the client’s written booking and Style Profile data. Continue?"))return;setBusy(true);setError("");setNotice("");try{const response=await fetch(`/api/admin/data-requests/${current.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({status,resolutionNote:note})}),payload=await response.json() as {data?:{clientDataDeleted?:boolean};error?:{message?:string}};if(!response.ok)throw new Error(payload.error?.message);setNote("");setNotice(payload.data?.clientDataDeleted?"Client data deleted and the minimal request audit retained.":"Privacy request updated.");await load();}catch(e){setError(e instanceof Error?e.message:"The privacy request could not be updated.");}finally{setBusy(false);}}
  async function runMaintenance(){if(!window.confirm("Run expired-link revocation and due retention deletion now?"))return;setBusy(true);setError("");setNotice("");try{const response=await fetch("/api/admin/operations/maintenance",{method:"POST"}),payload=await response.json() as {data?:{revokedExpiredTokenCount:number;deletedClientCount:number};error?:{message?:string}};if(!response.ok)throw new Error(payload.error?.message);setNotice(`Maintenance completed: ${payload.data!.revokedExpiredTokenCount} expired links revoked and ${payload.data!.deletedClientCount} due client records deleted.`);await load();}catch(e){setError(e instanceof Error?e.message:"Maintenance could not be completed.");}finally{setBusy(false);}}
  return <main className="admin-shell">
    <header className="admin-header"><div><p className="eyebrow">STYLE WITH KAYLA</p><h1>Privacy operations</h1><p>Signed in as {userName}</p></div><div className="admin-header-links"><a href="/admin">Appointment requests</a><a href="/admin/availability">Availability</a><a href={signOutPath}>Sign out</a></div></header>
    {error&&<p className="booking-error" role="alert">{error}</p>}{notice&&<p className="admin-notice" role="status">{notice}</p>}
    <section className="operations-summary" aria-label="Maintenance summary"><div><span>Open requests</span><strong>{summary?.openDataRequestCount??"—"}</strong></div><div><span>Expired private links</span><strong>{summary?.expiredTokenCount??"—"}</strong></div><div><span>Records due for deletion</span><strong>{summary?.dueClientCount??"—"}</strong></div><button className="primary-button" disabled={busy} onClick={()=>void runMaintenance()}>Run maintenance now</button></section>
    <section className="privacy-create action-panel"><h2>Record a client request</h2><p>Use the email already stored with the client. Contact remains the intake path; this creates the auditable work item.</p><div className="privacy-form"><label>Client email<input type="email" value={email} onChange={event=>setEmail(event.target.value)}/></label><label>Request type<select value={kind} onChange={event=>setKind(event.target.value)}><option value="access">Access</option><option value="correction">Correction</option><option value="deletion">Deletion</option></select></label><label className="wide">Request details<textarea value={details} onChange={event=>setDetails(event.target.value)} maxLength={2000}/></label></div><button className="primary-button" disabled={busy||!email} onClick={()=>void createRequest()}>Record request</button></section>
    <div className="privacy-toolbar"><label>Show <select value={filter} onChange={event=>{setFilter(event.target.value);setSelected("");}}><option value="active">Open and in progress</option><option value="all">All requests</option><option value="completed">Completed</option><option value="declined">Declined</option></select></label></div>
    <div className="admin-layout"><section className="request-list" aria-label="Privacy requests">{requests.length?requests.map(item=><button key={item.id} className={selected===item.id?"selected":""} onClick={()=>{setSelected(item.id);setNote("");}}><span><strong>{item.clientName}</strong><i>{item.kind}</i></span><span>{item.clientEmail}</span><span>{fmt(item.requestedAt)}</span><small>{item.status.replace("_"," ")}{item.activeBookingCount?` · ${item.activeBookingCount} active appointment`:""}</small></button>):<p>No matching privacy requests.</p>}</section>
      <section className="request-detail">{current?<><div className="detail-heading"><div><p className="small-label">{current.kind} request</p><h2>{current.clientName}</h2><p>{current.clientEmail}</p></div><span className="status-pill">{current.status.replace("_"," ")}</span></div><dl><div><dt>Received</dt><dd>{fmt(current.requestedAt)}</dd></div><div><dt>Active appointments</dt><dd>{current.activeBookingCount}</dd></div>{current.requestDetails&&<div className="wide"><dt>Request details</dt><dd>{current.requestDetails}</dd></div>}{current.resolutionNote&&<div className="wide"><dt>Resolution</dt><dd>{current.resolutionNote}</dd></div>}</dl><a className="admin-export" href={`/api/admin/data-requests/${current.id}/export`}>Download client data export</a>{new Set(["open","in_progress"]).has(current.status)&&<div className="action-panel"><h3>Resolve request</h3><label>Resolution note {current.status==="in_progress"?"(required to close)":""}<textarea value={note} onChange={event=>setNote(event.target.value)} maxLength={2000}/></label>{current.kind==="deletion"&&current.activeBookingCount>0&&<p className="warning-copy">Deletion is blocked until active appointments are cancelled or declined.</p>}<div><button disabled={busy||current.status==="in_progress"} onClick={()=>void updateRequest("in_progress")}>Mark in progress</button><button className="primary-button" disabled={busy||!note||(current.kind==="deletion"&&current.activeBookingCount>0)} onClick={()=>void updateRequest("completed")}>{current.kind==="deletion"?"Complete and delete data":"Complete request"}</button><button className="danger" disabled={busy||!note} onClick={()=>void updateRequest("declined")}>Decline</button></div></div>}</>:<p>Select a request to review it.</p>}</section></div>
  </main>;
}

