"use client";
import { FormEvent, useRef, useState } from "react";
import styles from "./event-page.module.css";

type EventData = Record<string, unknown> & { id?: unknown; slug?: unknown; ctaAction?: unknown; ctaLabel?: unknown };
const registerable = new Set(["registration","appointment","interest_list"]);

export default function EventPageActions({event,isPast}:{event:EventData;isPast:boolean}) {
  const dialog=useRef<HTMLDialogElement>(null),[detail,setDetail]=useState<EventData|null>(null),[message,setMessage]=useState(""),[submitting,setSubmitting]=useState(false),[copied,setCopied]=useState(false);
  const action=String(event.ctaAction||"none"), label=String(event.ctaLabel||"Learn More");
  const direct=action==="external_url"?String(event.ctaUrl):action==="email"?`mailto:${event.ctaEmail}`:action==="phone"?`tel:${event.ctaPhone}`:action==="add_to_calendar"?`/api/events/${event.id}/calendar`:"";
  async function openRegistration(){setMessage("Loading registration options…");dialog.current?.showModal();const response=await fetch(`/api/events/${encodeURIComponent(String(event.id))}`);const body=await response.json();if(!response.ok){setMessage(body.error?.message||"Registration options could not be loaded.");return;}setDetail(body.data.event);setMessage("");}
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setSubmitting(true);setMessage("Saving your spot…");const data=new FormData(e.currentTarget);const response=await fetch(`/api/events/${encodeURIComponent(String(event.id))}/rsvps`,{method:"POST",headers:{"content-type":"application/json","idempotency-key":crypto.randomUUID()},body:JSON.stringify({name:data.get("name"),email:data.get("email"),phone:data.get("phone")||undefined,guestCount:Number(data.get("guestCount")||0),notes:data.get("notes")||undefined,appointmentSlotId:data.get("appointmentSlotId")||undefined})});const body=await response.json();setSubmitting(false);if(!response.ok){setMessage(body.error?.message||"We could not complete registration.");return;}setMessage(`You’re registered! We saved ${body.data.registration.partySize} spot${body.data.registration.partySize===1?"":"s"}.`);}
  async function copyUrl(url:string){if(navigator.clipboard?.writeText){await navigator.clipboard.writeText(url);return;}const input=document.createElement("textarea");input.value=url;input.setAttribute("readonly","");input.style.position="fixed";input.style.opacity="0";document.body.append(input);input.select();document.execCommand("copy");input.remove();}
  async function share(){const url=`${location.origin}/events/${event.slug}`,text=String(event.shareMessage||"");try{if(navigator.share)await navigator.share({title:String(event.title),text,url});else{await copyUrl(url);setCopied(true);}}catch(error){if(error instanceof DOMException&&error.name==="AbortError")return;await copyUrl(url);setCopied(true);}}
  const showPrimary=action!=="none"&&action!=="information"&&!isPast;
  return <section className={styles.actions} aria-label="Event actions">
    {showPrimary&&(direct?<a className={styles.primary} href={direct}>{label}</a>:registerable.has(action)?<button className={styles.primary} type="button" onClick={openRegistration}>{label}</button>:null)}
    <div className={styles.secondary}><a href={`/api/events/${event.id}/calendar`}>Save to Calendar</a>{Boolean(event.sharingEnabled)&&<button type="button" onClick={share}>{copied?"Link Copied":"Share Event"}</button>}</div>
    <dialog ref={dialog} className={styles.dialog} aria-labelledby="event-rsvp-title"><form onSubmit={submit}><button className={styles.close} type="button" aria-label="Close registration" onClick={()=>dialog.current?.close()}>×</button><h2 id="event-rsvp-title">{label} — {String(event.title)}</h2>{detail&&<div className={styles.form}><label>Name<input name="name" required maxLength={120}/></label><label>Email<input name="email" type="email" required maxLength={254}/></label><label>Phone<input name="phone" type="tel" maxLength={40}/></label>{Number(detail.maxGuests)>0&&<label>Number of guests<input name="guestCount" type="number" min="0" max={Number(detail.maxGuests)} defaultValue="0"/></label>}{Boolean(detail.appointmentRequired)||detail.attendanceType==="appointment_recommended"?<label>Appointment time<select name="appointmentSlotId" required={Boolean(detail.appointmentRequired)}><option value="">{detail.appointmentRequired?"Choose a time":"Choose a time (optional)"}</option>{(detail.appointmentSlots as Array<Record<string,unknown>>||[]).map(slot=><option key={String(slot.id)} value={String(slot.id)}>{String(slot.label||new Date(String(slot.startsAt)).toLocaleTimeString([],{hour:"numeric",minute:"2-digit"}))}</option>)}</select></label>:null}<label>Notes<textarea name="notes" maxLength={1000}/></label><button className={styles.primary} disabled={submitting}>{submitting?"Saving…":label}</button></div>}<p role="status">{message}</p></form></dialog>
  </section>;
}
