import { requireAdmin } from "@/lib/server/admin-auth";
import { ApiError, dataResponse, optionalString, readJsonObject, rejectUnexpectedKeys, requiredString, validation, withApi } from "@/lib/server/http";
import { getD1 } from "@/lib/server/runtime";

type Params = { params: Promise<{ bookingId: string }> };
type Row = Record<string, unknown>;
const recapStatuses = new Set(["not_started", "draft", "ready_for_review", "published", "archived"]);
const editableStatuses = new Set(["not_started", "draft", "ready_for_review"]);
const outcomes = new Set(["great_success", "good_progress", "partial_success", "research_needed", "no_purchase_useful_discovery"]);
const categories = new Set(["fit", "silhouette", "color", "fabric", "comfort", "brand", "size", "styling", "lifestyle", "preference", "other"]);
const importanceLevels = new Set(["low", "medium", "high"]);
const priorityStatuses = new Set(["open", "in_progress", "completed", "no_longer_needed"]);

function boolean(value: unknown, field: string) { if (typeof value !== "boolean") throw validation(field, "Choose yes or no."); return value; }
function choice(value: unknown, field: string, allowed: Set<string>, nullable = false) { if (nullable && (value === null || value === undefined || value === "")) return null; if (typeof value !== "string" || !allowed.has(value)) throw validation(field, "Choose a valid option."); return value; }
function objects(value: unknown, field: string) { if (value === undefined) return []; if (!Array.isArray(value)) throw validation(field, "Submit a list."); return value.map((item, index) => { if (!item || typeof item !== "object" || Array.isArray(item)) throw validation(`${field}.${index}`, "Submit a valid row."); return item as Record<string, unknown>; }); }
function optionalId(value: unknown, field: string) { return value === undefined ? null : requiredString(value, field, 100); }

async function loadRecap(db: D1Database, bookingId: string) {
  const recap = await db.prepare(`SELECT id,booking_id AS bookingId,client_id AS clientId,status,outcome,what_we_solved AS whatWeSolved,kayla_note AS kaylaNote,next_moment_service_type AS nextMomentServiceType,next_moment_timing AS nextMomentTiming,next_moment_reason AS nextMomentReason,next_moment_booking_cta_enabled AS nextMomentBookingCtaEnabled,private_follow_up_note AS privateFollowUpNote,created_at AS createdAt,updated_at AS updatedAt FROM appointment_recaps WHERE booking_id=?`).bind(bookingId).first<Row>();
  if (!recap) throw new ApiError(404, "RECAP_NOT_FOUND", "This booking does not have an appointment recap yet.");
  recap.nextMomentBookingCtaEnabled = Boolean(recap.nextMomentBookingCtaEnabled);
  recap.createdAt = new Date(recap.createdAt as number).toISOString(); recap.updatedAt = new Date(recap.updatedAt as number).toISOString();
  const [insightsResult, itemsResult, formulasResult, prioritiesResult] = await Promise.all([
    db.prepare(`SELECT id,polarity,category,insight_text AS insightText,client_facing AS clientFacing,importance,sort_order AS sortOrder,saved_to_client_notes AS savedToClientNotes,client_style_note_id AS clientStyleNoteId FROM recap_insights WHERE recap_id=? ORDER BY sort_order ASC`).bind(recap.id).all<Row>(),
    db.prepare(`SELECT id,item_name AS itemName,brand,size,color,category,note,disposition,client_facing AS clientFacing,sort_order AS sortOrder FROM recap_items WHERE recap_id=? ORDER BY sort_order ASC`).bind(recap.id).all<Row>(),
    db.prepare(`SELECT id,formula_text AS formulaText,explanation,sort_order AS sortOrder FROM recap_formulas WHERE recap_id=? ORDER BY sort_order ASC`).bind(recap.id).all<Row>(),
    db.prepare(`SELECT id,category,priority_text AS priorityText,status,rank,client_facing AS clientFacing FROM recap_priorities WHERE recap_id=? ORDER BY rank ASC`).bind(recap.id).all<Row>(),
  ]);
  return { recap, insights: insightsResult.results.map(row => ({ ...row, clientFacing: Boolean(row.clientFacing), savedToClientNotes: Boolean(row.savedToClientNotes) })), items: itemsResult.results.map(row => ({ ...row, clientFacing: Boolean(row.clientFacing) })), formulas: formulasResult.results, priorities: prioritiesResult.results.map(row => ({ ...row, clientFacing: Boolean(row.clientFacing) })) };
}

export async function GET(request: Request, ctx: Params) { return withApi(async id => { requireAdmin(request); const { bookingId } = await ctx.params, db = getD1(), now = Date.now(); const booking = await db.prepare(`SELECT client_id AS clientId FROM bookings WHERE id=?`).bind(bookingId).first<{clientId:string}>(); if (!booking) throw new ApiError(404, "BOOKING_NOT_FOUND", "Booking request not found."); await db.prepare(`INSERT INTO appointment_recaps(id,booking_id,client_id,status,created_at,updated_at) VALUES(?,?,?,'not_started',?,?) ON CONFLICT(booking_id) DO NOTHING`).bind(crypto.randomUUID(), bookingId, booking.clientId, now, now).run(); return dataResponse(await loadRecap(db, bookingId), 200, id); }); }

export async function PATCH(request: Request, ctx: Params) { return withApi(async requestId => {
  const adminEmail = requireAdmin(request), { bookingId } = await ctx.params, body = await readJsonObject(request); void adminEmail;
  rejectUnexpectedKeys(body, ["status","outcome","whatWeSolved","kaylaNote","nextMomentServiceType","nextMomentTiming","nextMomentReason","nextMomentBookingCtaEnabled","privateFollowUpNote","insights","items","formulas","priorities"]);
  const db = getD1(), current = await db.prepare(`SELECT id,status,outcome,what_we_solved AS whatWeSolved,kayla_note AS kaylaNote,next_moment_service_type AS nextMomentServiceType,next_moment_timing AS nextMomentTiming,next_moment_reason AS nextMomentReason,next_moment_booking_cta_enabled AS nextMomentBookingCtaEnabled,private_follow_up_note AS privateFollowUpNote FROM appointment_recaps WHERE booking_id=?`).bind(bookingId).first<Row>();
  if (!current) throw new ApiError(404, "RECAP_NOT_FOUND", "Open the appointment wrap-up before saving it.");
  const status = body.status === undefined ? String(current.status) : choice(body.status, "status", recapStatuses); if (!editableStatuses.has(status!)) throw validation("status", "Published and archived recaps cannot be changed here.");
  const outcome = body.outcome === undefined ? current.outcome : choice(body.outcome, "outcome", outcomes, true);
  const scalar = (key: string, max: number) => body[key] === undefined ? current[key] : optionalString(body[key], key, max);
  const whatWeSolved = scalar("whatWeSolved", 2000), kaylaNote = scalar("kaylaNote", 400), nextMomentServiceType = scalar("nextMomentServiceType", 200), nextMomentTiming = scalar("nextMomentTiming", 200), nextMomentReason = scalar("nextMomentReason", 500), privateFollowUpNote = scalar("privateFollowUpNote", 2000);
  const nextMomentBookingCtaEnabled = body.nextMomentBookingCtaEnabled === undefined ? Boolean(current.nextMomentBookingCtaEnabled) : boolean(body.nextMomentBookingCtaEnabled, "nextMomentBookingCtaEnabled");
  const insights = objects(body.insights, "insights").map((row,index) => { rejectUnexpectedKeys(row,["id","polarity","category","insightText","clientFacing","importance"],`insights.${index}`); return { id:optionalId(row.id,`insights.${index}.id`), polarity:choice(row.polarity,`insights.${index}.polarity`,new Set(["worked","didnt_work"])), category:choice(row.category,`insights.${index}.category`,categories), insightText:requiredString(row.insightText,`insights.${index}.insightText`,500), clientFacing:boolean(row.clientFacing,`insights.${index}.clientFacing`), importance:choice(row.importance,`insights.${index}.importance`,importanceLevels,true) }; });
  const items = objects(body.items,"items").map((row,index)=>{rejectUnexpectedKeys(row,["id","itemName","brand","size","color","category","note","disposition","clientFacing"],`items.${index}`);return{id:optionalId(row.id,`items.${index}.id`),itemName:requiredString(row.itemName,`items.${index}.itemName`,200),brand:optionalString(row.brand,`items.${index}.brand`,200),size:optionalString(row.size,`items.${index}.size`,100),color:optionalString(row.color,`items.${index}.color`,100),category:optionalString(row.category,`items.${index}.category`,100),note:optionalString(row.note,`items.${index}.note`,500),disposition:choice(row.disposition,`items.${index}.disposition`,new Set(["purchased","considered"])),clientFacing:boolean(row.clientFacing,`items.${index}.clientFacing`)};});
  const formulas = objects(body.formulas,"formulas"); if(formulas.length>8)throw validation("formulas","Submit no more than 8 outfit formulas."); const parsedFormulas=formulas.map((row,index)=>{rejectUnexpectedKeys(row,["id","formulaText","explanation"],`formulas.${index}`);return{id:optionalId(row.id,`formulas.${index}.id`),formulaText:requiredString(row.formulaText,`formulas.${index}.formulaText`,200),explanation:optionalString(row.explanation,`formulas.${index}.explanation`,500)};});
  const priorities=objects(body.priorities,"priorities").map((row,index)=>{rejectUnexpectedKeys(row,["id","category","priorityText","status","clientFacing"],`priorities.${index}`);return{id:optionalId(row.id,`priorities.${index}.id`),category:optionalString(row.category,`priorities.${index}.category`,100),priorityText:requiredString(row.priorityText,`priorities.${index}.priorityText`,200),status:choice(row.status,`priorities.${index}.status`,priorityStatuses),clientFacing:boolean(row.clientFacing,`priorities.${index}.clientFacing`)};});
  const retained = new Map((await db.prepare(`SELECT id,saved_to_client_notes AS savedToClientNotes,client_style_note_id AS clientStyleNoteId FROM recap_insights WHERE recap_id=?`).bind(current.id).all<{id:string;savedToClientNotes:number;clientStyleNoteId:string|null}>()).results.map(row=>[row.id,row]));
  const now=Date.now(), statements=[db.prepare(`UPDATE appointment_recaps SET status=?,outcome=?,what_we_solved=?,kayla_note=?,next_moment_service_type=?,next_moment_timing=?,next_moment_reason=?,next_moment_booking_cta_enabled=?,private_follow_up_note=?,updated_at=? WHERE id=?`).bind(status,outcome,whatWeSolved,kaylaNote,nextMomentServiceType,nextMomentTiming,nextMomentReason,nextMomentBookingCtaEnabled?1:0,privateFollowUpNote,now,current.id),db.prepare(`DELETE FROM recap_insights WHERE recap_id=?`).bind(current.id),...insights.map((row,index)=>{const old=row.id?retained.get(row.id):undefined;return db.prepare(`INSERT INTO recap_insights(id,recap_id,polarity,category,insight_text,client_facing,importance,sort_order,saved_to_client_notes,client_style_note_id,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)`).bind(row.id??crypto.randomUUID(),current.id,row.polarity,row.category,row.insightText,row.clientFacing?1:0,row.importance,index,old?.savedToClientNotes??0,old?.clientStyleNoteId??null,now);}),db.prepare(`DELETE FROM recap_items WHERE recap_id=?`).bind(current.id),...items.map((row,index)=>db.prepare(`INSERT INTO recap_items(id,recap_id,item_name,brand,size,color,category,note,disposition,client_facing,sort_order,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)`).bind(row.id??crypto.randomUUID(),current.id,row.itemName,row.brand,row.size,row.color,row.category,row.note,row.disposition,row.clientFacing?1:0,index,now)),db.prepare(`DELETE FROM recap_formulas WHERE recap_id=?`).bind(current.id),...parsedFormulas.map((row,index)=>db.prepare(`INSERT INTO recap_formulas(id,recap_id,formula_text,explanation,sort_order,created_at) VALUES(?,?,?,?,?,?)`).bind(row.id??crypto.randomUUID(),current.id,row.formulaText,row.explanation,index,now)),db.prepare(`DELETE FROM recap_priorities WHERE recap_id=?`).bind(current.id),...priorities.map((row,index)=>db.prepare(`INSERT INTO recap_priorities(id,recap_id,category,priority_text,status,rank,client_facing,created_at) VALUES(?,?,?,?,?,?,?,?)`).bind(row.id??crypto.randomUUID(),current.id,row.category,row.priorityText,row.status,index,row.clientFacing?1:0,now))];
  await db.batch(statements); return dataResponse(await loadRecap(db,bookingId),200,requestId);
}); }
