import{ApiError,dataResponse,optionalString,readJsonObject,rejectUnexpectedKeys,requiredString,validation,withApi}from"@/lib/server/http";import{randomPublicReference,sha256}from"@/lib/server/crypto";import{getD1}from"@/lib/server/runtime";import{calculateAvailability,getActiveService,localDateKey}from"@/lib/server/scheduling";
type Existing={id:string;publicReference:string;status:string;serviceName:string;requestedStartAt:number;requestedEndAt:number;payloadHash:string};
const heard=new Set(["Instagram","Facebook","In-store","Referral","Macy's event","Other"]);
export async function POST(request:Request){return withApi(async requestId=>{
 const body=await readJsonObject(request);rejectUnexpectedKeys(body,["client","serviceCode","requestedStartAt","returningClient","howHeard","ageRange","eventType","eventDate","bookingNotes","privacy"]);
 const client=obj(body.client,"client"),privacy=obj(body.privacy,"privacy");rejectUnexpectedKeys(client,["fullName","email","phone"],"client");rejectUnexpectedKeys(privacy,["policyVersion","acknowledged"],"privacy");
 const fullName=requiredString(client.fullName,"client.fullName",120),email=requiredString(client.email,"client.email",254),normalizedEmail=email.toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(normalizedEmail))throw validation("client.email","Enter a valid email address.");
 const phone=requiredString(client.phone,"client.phone",40),normalizedPhone=phone.replace(/\D/g,"");if(normalizedPhone.length<7||normalizedPhone.length>15)throw validation("client.phone","Enter a valid phone number.");
 const serviceCode=requiredString(body.serviceCode,"serviceCode",60),startText=requiredString(body.requestedStartAt,"requestedStartAt",40),start=Date.parse(startText);if(!Number.isFinite(start)||new Date(start).toISOString()!==startText)throw validation("requestedStartAt","Choose an available appointment time.");
 if(typeof body.returningClient!=="boolean")throw validation("returningClient","Choose yes or no.");const returning=body.returningClient,howHeard=returning?"Returning Client":requiredString(body.howHeard,"howHeard",80);if(!returning&&!heard.has(howHeard))throw validation("howHeard","Choose one of the available options.");if(privacy.acknowledged!==true)throw validation("privacy.acknowledged","Please acknowledge the privacy notice.");const policy=requiredString(privacy.policyVersion,"privacy.policyVersion",40);
 const db=getD1(),service=await getActiveService(db,serviceCode);let ageRange:string|null=null,profileType:string|null=null,eventType:string|null=null,eventDate:string|null=null;
 if(service.routingMode==="age"){profileType="womens_styling";}else if(service.routingMode==="womens_event"||service.routingMode==="mens_event"){eventType=requiredString(body.eventType,"eventType",120);eventDate=requiredString(body.eventDate,"eventDate",10);if(!/^\d{4}-\d{2}-\d{2}$/.test(eventDate))throw validation("eventDate","Choose a valid event date.");profileType=service.routingMode;}else profileType="mens_styling";
 const notes=optionalString(body.bookingNotes,"bookingNotes",2000),date=localDateKey(start,"America/Boise"),availability=await calculateAvailability(db,serviceCode,date,date),slot=availability.slots.find(x=>x.startsAt===startText);if(!slot)throw new ApiError(409,"SLOT_UNAVAILABLE","That appointment time is no longer available.",{requestedStartAt:"Choose another available time."});const end=Date.parse(slot.endsAt);
 const canonical=JSON.stringify({fullName,normalizedEmail,phone,serviceCode,startText,returning,howHeard,ageRange,eventType,eventDate,notes,policy}),payloadHash=await sha256(canonical),key=request.headers.get("idempotency-key")?.trim()||crypto.randomUUID();if(key.length>200)throw new ApiError(400,"INVALID_IDEMPOTENCY_KEY","The idempotency key is too long.");const keyHash=await sha256(key);
 const existing=await findExisting(db,keyHash);if(existing){if(existing.payloadHash!==payloadHash)throw new ApiError(409,"IDEMPOTENCY_KEY_REUSED","This submission key was already used for a different request.");return response(existing,requestId);}
 const ip=request.headers.get("cf-connecting-ip")??request.headers.get("x-forwarded-for")?.split(",")[0]?.trim()??"unknown",rateHash=await sha256(`${ip}\n${normalizedEmail}`),count=await db.prepare(`SELECT COUNT(*) AS count FROM booking_status_history WHERE created_at>=? AND json_extract(metadata,'$.rateLimitKeyHash')=?`).bind(Date.now()-3600000,rateHash).first<{count:number}>();if((count?.count??0)>=5)throw new ApiError(429,"RATE_LIMITED","Too many requests were submitted. Please try again later.");
 const now=Date.now(),bookingId=crypto.randomUUID(),publicReference=randomPublicReference(),meta=JSON.stringify({idempotencyKeyHash:keyHash,payloadHash,rateLimitKeyHash:rateHash,action:"public_submission"});
 await db.batch([
 db.prepare(`INSERT INTO clients(id,full_name,email,normalized_email,phone,normalized_phone,created_at,updated_at)VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(normalized_email) DO UPDATE SET full_name=excluded.full_name,email=excluded.email,phone=excluded.phone,normalized_phone=excluded.normalized_phone,updated_at=excluded.updated_at`).bind(crypto.randomUUID(),fullName,email,normalizedEmail,phone,normalizedPhone,now,now),
 db.prepare(`INSERT INTO bookings(id,public_reference,client_id,service_id,status,requested_start_at,requested_end_at,returning_client,how_heard,age_range,profile_type,event_type,event_date,booking_notes,privacy_policy_version,privacy_acknowledged_at,pending_since,created_at,updated_at) SELECT ?,?,c.id,?,'pending',?,?,?,?,?,?,?,?,?,?,?,?,?,? FROM clients c WHERE c.normalized_email=? AND NOT EXISTS(SELECT 1 FROM booking_holds h WHERE h.active=1 AND h.starts_at<? AND h.ends_at>?)`).bind(bookingId,publicReference,service.id,start,end,returning?1:0,howHeard,ageRange,profileType,eventType,eventDate,notes,policy,now,now,now,now,normalizedEmail,end,start),
 db.prepare(`INSERT INTO booking_holds(id,booking_id,kind,starts_at,ends_at,active,created_at) SELECT ?,id,'requested',requested_start_at,requested_end_at,1,? FROM bookings WHERE id=?`).bind(crypto.randomUUID(),now,bookingId),
 db.prepare(`INSERT INTO booking_status_history(id,booking_id,from_status,to_status,actor_type,metadata,created_at) SELECT ?,id,NULL,'pending','client',?,? FROM bookings WHERE id=?`).bind(crypto.randomUUID(),meta,now,bookingId),
 db.prepare(`INSERT INTO communications(id,booking_id,channel,template_key,recipient,status,metadata,created_at) SELECT ?,id,'email','booking_request_received',?,'recorded',?,? FROM bookings WHERE id=?`).bind(crypto.randomUUID(),email,JSON.stringify({deliveryDeferred:true}),now,bookingId)]);
 const created=await db.prepare(`SELECT b.id,b.public_reference AS publicReference,b.status,s.name AS serviceName,b.requested_start_at AS requestedStartAt,b.requested_end_at AS requestedEndAt,? AS payloadHash FROM bookings b JOIN services s ON s.id=b.service_id WHERE b.id=?`).bind(payloadHash,bookingId).first<Existing>();if(!created)throw new ApiError(409,"SLOT_UNAVAILABLE","That appointment time is no longer available.",{requestedStartAt:"Choose another available time."});return response(created,requestId);
});}
async function findExisting(db:D1Database,key:string){return db.prepare(`SELECT b.id,b.public_reference AS publicReference,b.status,s.name AS serviceName,b.requested_start_at AS requestedStartAt,b.requested_end_at AS requestedEndAt,json_extract(h.metadata,'$.payloadHash') AS payloadHash FROM booking_status_history h JOIN bookings b ON b.id=h.booking_id JOIN services s ON s.id=b.service_id WHERE json_extract(h.metadata,'$.idempotencyKeyHash')=? ORDER BY h.created_at DESC LIMIT 1`).bind(key).first<Existing>();}
function response(b:Existing,id:string){return dataResponse({publicReference:b.publicReference,status:b.status,serviceName:b.serviceName,requestedStartAt:new Date(b.requestedStartAt).toISOString(),requestedEndAt:new Date(b.requestedEndAt).toISOString()},201,id);}function obj(v:unknown,field:string){if(!v||typeof v!=="object"||Array.isArray(v))throw validation(field,"This section is required.");return v as Record<string,unknown>;}
