"use client";import{useCallback,useEffect,useState}from"react";
type Rule={weekday:number;startMinute:number;endMinute:number};type Override={id:string;kind:"available"|"unavailable";startsAt:string;endsAt:string;note:string|null};const days=[[2,"Tuesday"],[3,"Wednesday"],[4,"Thursday"],[5,"Friday"],[6,"Saturday"]] as const;
const asTime=(minutes:number)=>`${String(Math.floor(minutes/60)).padStart(2,"0")}:${String(minutes%60).padStart(2,"0")}`,asMinutes=(value:string)=>{const[h,m]=value.split(":").map(Number);return h*60+m;};
function boiseLocalToIso(value:string){const[date,time]=value.split("T"),[year,month,day]=date.split("-").map(Number),[hour,minute]=time.split(":").map(Number),target=Date.UTC(year,month-1,day,hour,minute);let epoch=target;for(let i=0;i<4;i++){const parts=new Intl.DateTimeFormat("en-US",{timeZone:"America/Boise",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hourCycle:"h23"}).formatToParts(epoch),part=(type:string)=>Number(parts.find(item=>item.type===type)?.value),represented=Date.UTC(part("year"),part("month")-1,part("day"),part("hour"),part("minute")),correction=target-represented;epoch+=correction;if(!correction)break;}return new Date(epoch).toISOString();}
const fmt=(value:string)=>new Intl.DateTimeFormat("en-US",{timeZone:"America/Boise",dateStyle:"medium",timeStyle:"short"}).format(new Date(value));
export default function AdminAvailability({userName,signOutPath}:{userName:string;signOutPath:string}){const[rules,setRules]=useState<Rule[]>([]),[overrides,setOverrides]=useState<Override[]>([]),[error,setError]=useState(""),[saved,setSaved]=useState(""),[kind,setKind]=useState<"available"|"unavailable">("unavailable"),[startsAt,setStartsAt]=useState(""),[endsAt,setEndsAt]=useState(""),[note,setNote]=useState("");
 const load=useCallback(async()=>{setError("");try{const r=await fetch("/api/admin/settings/availability",{cache:"no-store"}),p=await r.json() as {data?:{rules:Rule[];overrides:Override[]};error?:{message?:string}};if(!r.ok)throw new Error(p.error?.message);setRules(p.data!.rules);setOverrides(p.data!.overrides);}catch(e){setError(e instanceof Error?e.message:"Availability could not be loaded.");}},[]);useEffect(()=>{void Promise.resolve().then(load);},[load]);
 function change(day:number,index:number,key:"startMinute"|"endMinute",value:string){const dayRules=rules.filter(rule=>rule.weekday===day);const target=dayRules[index],next=rules.map(rule=>rule===target?{...rule,[key]:asMinutes(value)}:rule);setRules(next);}
 function addWindow(day:number){setRules(current=>[...current,{weekday:day,startMinute:630,endMinute:810}]);}function removeWindow(day:number,index:number){const target=rules.filter(rule=>rule.weekday===day)[index];setRules(current=>current.filter(rule=>rule!==target));}
 async function saveRules(){setError("");setSaved("");try{const r=await fetch("/api/admin/settings/availability",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({rules})}),p=await r.json() as {error?:{message?:string}};if(!r.ok)throw new Error(p.error?.message);setSaved("Routine availability saved.");await load();}catch(e){setError(e instanceof Error?e.message:"Routine availability could not be saved.");}}
 async function addOverride(){setError("");try{const r=await fetch("/api/admin/settings/availability/overrides",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({kind,startsAt:boiseLocalToIso(startsAt),endsAt:boiseLocalToIso(endsAt),note:note||null})}),p=await r.json() as {error?:{message?:string}};if(!r.ok)throw new Error(p.error?.message);setStartsAt("");setEndsAt("");setNote("");await load();}catch(e){setError(e instanceof Error?e.message:"Override could not be added.");}}
 async function removeOverride(id:string){setError("");try{const r=await fetch(`/api/admin/settings/availability/overrides/${id}`,{method:"DELETE"}),p=await r.json() as {error?:{message?:string}};if(!r.ok)throw new Error(p.error?.message);await load();}catch(e){setError(e instanceof Error?e.message:"Override could not be removed.");}}
 return <main className="admin-shell"><header className="admin-header"><div><p className="eyebrow">STYLE WITH KAYLA</p><h1>Availability settings</h1><p>Times are shown in America/Boise · Signed in as {userName}</p></div><div className="admin-header-links"><a href="/admin">Appointment requests</a><a href={signOutPath}>Sign out</a></div></header>{error&&<p className="booking-error" role="alert">{error}</p>}{saved&&<p className="admin-success" role="status">{saved}</p>}
 <section className="availability-card"><div className="availability-title"><div><p className="small-label">ROUTINE WINDOWS</p><h2>Weekly availability</h2></div><button className="primary-button" onClick={()=>void saveRules()}>Save routine</button></div>{days.map(([day,label])=><div className="availability-day" key={day}><strong>{label}</strong><div>{rules.filter(rule=>rule.weekday===day).map((rule,index)=><div className="window-row" key={`${day}-${index}`}><input aria-label={`${label} start`} type="time" value={asTime(rule.startMinute)} onChange={e=>change(day,index,"startMinute",e.target.value)}/><span>to</span><input aria-label={`${label} end`} type="time" value={asTime(rule.endMinute)} onChange={e=>change(day,index,"endMinute",e.target.value)}/><button onClick={()=>removeWindow(day,index)}>Remove</button></div>)}<button className="add-window" onClick={()=>addWindow(day)}>+ Add window</button></div></div>)}</section>
 <section className="availability-card"><p className="small-label">ONE-OFF CHANGES</p><h2>Availability overrides</h2><div className="override-form"><label>Type<select value={kind} onChange={e=>setKind(e.target.value as typeof kind)}><option value="unavailable">Block time</option><option value="available">Add available time</option></select></label><label>Starts<input type="datetime-local" value={startsAt} onChange={e=>setStartsAt(e.target.value)}/></label><label>Ends<input type="datetime-local" value={endsAt} onChange={e=>setEndsAt(e.target.value)}/></label><label className="wide">Note<input value={note} onChange={e=>setNote(e.target.value)}/></label><button className="primary-button" disabled={!startsAt||!endsAt} onClick={()=>void addOverride()}>Add override</button></div><div className="override-list">{overrides.length?overrides.map(item=><div key={item.id}><span className={`status-pill ${item.kind}`}>{item.kind}</span><p><strong>{fmt(item.startsAt)}</strong> to <strong>{fmt(item.endsAt)}</strong>{item.note&&<><br/>{item.note}</>}</p><button onClick={()=>void removeOverride(item.id)}>Remove</button></div>):<p>No upcoming overrides.</p>}</div></section></main>;
}
