"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { StyleSummarySections } from "@/components/StyleSummarySections";
import type { RecapSummaryContent } from "@/lib/server/recap-policy";

export default function RecapPreview({ bookingId, userName, signOutPath }: { bookingId: string; userName: string; signOutPath: string }) {
  const [content, setContent] = useState<RecapSummaryContent | null>(null), [error, setError] = useState(""), [publishing, setPublishing] = useState(false), [sending,setSending]=useState(false), [link, setLink] = useState(""),[published,setPublished]=useState(false),[clientEmail,setClientEmail]=useState<string|null>(null),[sentAt,setSentAt]=useState<string|null>(null),[recipient,setRecipient]=useState<string|null>(null);
  useEffect(() => { fetch(`/api/admin/bookings/${bookingId}/recap/preview`, { cache: "no-store" }).then(async response => { const payload = await response.json() as { data?: {content:RecapSummaryContent;status:string;styleSummaryUrl:string|null;clientEmail:string|null;sentAt:string|null;recipient:string|null}; error?: { message?: string } }; if (!response.ok) throw new Error(payload.error?.message || "The preview could not be loaded."); const data=payload.data!;setContent(data.content);setPublished(data.status==="published");setLink(data.styleSummaryUrl??"");setClientEmail(data.clientEmail);setSentAt(data.sentAt);setRecipient(data.recipient); }).catch(reason => setError(reason instanceof Error ? reason.message : "The preview could not be loaded.")); }, [bookingId]);
  async function publish() { setPublishing(true); setError(""); try { const response = await fetch(`/api/admin/bookings/${bookingId}/recap/publish`, { method: "POST" }); const payload = await response.json() as { data?: { styleSummaryUrl: string }; error?: { message?: string } }; if (!response.ok) throw new Error(payload.error?.message || "The Style Summary could not be published."); setLink(payload.data!.styleSummaryUrl);setPublished(true); } catch (reason) { setError(reason instanceof Error ? reason.message : "The Style Summary could not be published."); } finally { setPublishing(false); } }
  async function sendEmail(){setSending(true);setError("");try{const response=await fetch(`/api/admin/bookings/${bookingId}/recap/send-email`,{method:"POST"});const payload=await response.json() as {data?:{recipient:string;sentAt:string};error?:{message?:string}};if(!response.ok)throw new Error(payload.error?.message||"The Style Summary is published, but the email could not be sent. Please try again.");setRecipient(payload.data!.recipient);setSentAt(payload.data!.sentAt);}catch(reason){setError(reason instanceof Error?reason.message:"The Style Summary is published, but the email could not be sent. Please try again.");}finally{setSending(false);}}
  return <main className="recap-preview-admin"><header className="admin-header"><div><p className="eyebrow">STYLE SUMMARY PREVIEW</p><h1>Review the client view</h1><p>Signed in as {userName}</p></div><div><Link href="/admin">Back to appointments</Link> · <a href={signOutPath}>Sign out</a></div></header>
    <div className="recap-preview-actions">{!published?<button className="primary-button" disabled={publishing || !content} onClick={() => void publish()}>{publishing ? "Publishing…" : "Publish Style Summary"}</button>:<strong>Published</strong>}{error && <p role="alert">{error}</p>}{link && <div className="profile-link-result"><strong>Private Style Summary link</strong><input readOnly value={link}/><button onClick={() => void navigator.clipboard.writeText(link)}>Copy link</button>{sentAt?<p>Email sent to {recipient}<br/>{new Date(sentAt).toLocaleString()}</p>:!clientEmail?<p>No client email address is available.</p>:null}{clientEmail&&<button className="primary-button" disabled={sending} onClick={()=>void sendEmail()}>{sending?"Sending…":sentAt?"Send Again":"Send Email"}</button>}</div>}</div>
    {content ? <div className="style-summary-page"><StyleSummarySections content={content}/></div> : !error && <p>Loading preview…</p>}
  </main>;
}
